### ISSUE TITLE
Sundsvalls Tidning

### ISSUE THREAD

**Issue by kebnekaise** [lassekongo83/Frellwits-filter-lists#1]
Är det möjligt att ta sig förbi [st.nu](https://www.st.nu/logga-in/saljer-armband-for-cancersjuka-barn-ger-hela-vinsten-till-familjerna):s betalväggar?

I så fall, skulle den kunna läggas till?

Tack!

**Comment by lassekongo83** [comment]
Tyvärr så är deras innehåll låst bakom en riktig betalvägg som kräver inloggning. https://www.reddit.com/r/sweden/comments/5t5l6k/posta_era_paywallfilter_f%C3%B6r_sidor_som_dn_di_svd/ddkptgq/
