### ISSUE TITLE
fanboy-swedish.txt merge

### ISSUE THREAD

**Issue by davidhedlund** [lassekongo83/Frellwits-filter-lists#10]
Have you tried to merge as much as possible from https://www.fanboy.co.nz/fanboy-swedish.txt (now the Swedish filter list in uBlock Origin) to https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Frellwits-Swedish-Filter.txt (the old Swedish filter list in uBlock Origin)?

**Comment by davidhedlund** [comment]
Tack för att du bokmärkte https://github.com/davidhedlund/EasyCrawler/stargazers förresten.

**Comment by davidhedlund** [comment]
Vänligen hör av dig om du har lust att ta över https://github.com/davidhedlund/EasyCrawler för officiell underhållning. Jag kommer i så fall skriva det på projektets sida och hänvisa till din fork.

**Comment by lassekongo83** [comment]
Tog tag i det som fortfarande var aktuellt. Mycket i den listan behövdes inte längre.

**Comment by davidhedlund** [comment]
Bra jobbat!

**Comment by davidhedlund** [comment]
I suggest that you mention https://github.com/ryanbr/fanboy-adblock/blob/master/firefox-regional/fanboy-adblocklist-swe.txt in https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Frellwits-Swedish-Filter.txt and https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/README.md to give some credit to Fanboy. What do you think?

**Comment by lassekongo83** [comment]
Added.

**Comment by davidhedlund** [comment]
Thanks.
