### ISSUE TITLE
kommunal.se - 

### ISSUE THREAD

**Issue by onisedki** [lassekongo83/Frellwits-filter-lists#101]
### Länk till sidan

`https://www.kommunal.se/`

### Beskriv problemet

Cookie notisen blockerar inloggnings knappen och den går inte att stänga.

### Versioner

- Webbläsare/version: 85.0.2 (64-bitars)
- uBlock Origin version: v1.33.2

### Inställningar

Allt är default. Ny firefox profil och installerade ublock origin bara.

**Comment by lassekongo83** [comment]
Vänta ca 10 min och kör sen en [manuell uppdatering av listan](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now).
