### ISSUE TITLE
Missed leftover

### ISSUE THREAD

**Issue by wout-codes** [lassekongo83/Frellwits-filter-lists#103]
### URL(s) where the issue occurs

`https://readmanga.se/manga/the-beginning-after-the-end/`

### Describe the issue

Ad leftover after scrolling a little down.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/76908410/108685018-96919200-752e-11eb-99eb-c96ca2fba971.png)

### Versions

- Browser/version: Opera 74.0.3911.154
- uBlock Origin version: 1.33.2

### Settings

Default uBO Lists + Frellwit's Swedish Filter

**Comment by lassekongo83** [comment]
Not a Swedish website. They just happen to use the .se top level domain. Report to [Easylist](https://github.com/easylist/easylist).
