### ISSUE TITLE
BT.no - Missing article images (Frellwit's Swedish Filter)

### ISSUE THREAD

**Issue by THEtomaso** [lassekongo83/Frellwits-filter-lists#106]
### Affected site:
`https://www.bt.no/`

### Issue:
Missing article images.

### Example:
`https://www.bt.no/btmeninger/debatt/i/41wXVa`

(Scroll down to see)

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **Frellwit's Swedish Filter**

### Problem rule:
`/hyperion-feature-ads`

### Possible fix:
`@@||bt.no^*/hyperion-feature-ads$script`

### Note:
The above fix solves the issue for Chromium.
However, during my tests, I noticed that the images still failed to load sometimes, when using Pale Moon.
This is possibly a browser-specific issue, limited to Firefox-based browsers.
I was able to properly solve the issue for Pale Moon too, by adding this additional rule, which completely blocks their internal GDPR assets:
`||cmp.bt.no^`
On a side note, I was already using the same blocking rule for a couple of other domains (seemingly without any ill effects):
`||cmp.tek.no^`
`||cmp.vg.no^`

### Additional issue:
Empty ad container (@DandelionSprout):
`bt.no##.disable-cogwheel`

(PS: Read my above "Note" too) 

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Chromium-ungoogled v89.0.4389.114-r843830 (x64) / Pale Moon v29.1.1 (x64)
* Adblock Extension/version: uBlock Origin v1.34.0 / v1.16.4.28 (XUL)

**Comment by lassekongo83** [comment]
For the cmp rules you can just use `/messagingNoTcfApi.js` for all.

**Comment by THEtomaso** [comment]
Think I'll keep those rules site-specific.
DS has already got a whitlisting for `ekstrabladet.dk`:
https://github.com/DandelionSprout/adfilt/blob/58338ae23a87fa393b8e93417d379965a7b43c4b/NorwegianList.txt#L1596

**Comment by DandelionSprout** [comment]
I'll go with:
```
bt.no###topstripes
bt.no##[data-variants*=article_netboard]:upward(1)
```

Regarding `cmp`, I presume `||cmp.*.no^` could've been suitable for IDCAC.

**Comment by THEtomaso** [comment]
@DandelionSprout:
When refresing the page, `bt.no###topstripes` doesn't work every time with Pale Moon (and possibly not with Firefox).
`bt.no##.disable-cogwheel`, otoh, works every time!

**Comment by DandelionSprout** [comment]
I'm feeling sleepy despite just having woken up, so I'll have to look into that overnight.

**Comment by THEtomaso** [comment]
> I'll have to look into that overnight.

When you get around to it, consider looking into these issues too:
https://github.com/ryanbr/fanboy-adblock/issues/1468/
https://github.com/ryanbr/fanboy-adblock/issues/1469/

I'm not sure what we agreed upon..
Do you include fixes in your filter only for Norwegian site's broken by ryanbr's cookie list, or will you include fixes for his annoyance list as well (like in these cases)?

**Comment by DandelionSprout** [comment]
The situation is roughly as follows:
• It seems to be complete bingo if Fanboy takes 4 hours or 4 months to fix reports. As such, I've occasionally held out on adding temp fixes right away to see if he fixes it, and then I've forgot the whole thing the next day.
• I attempted to reply to the fix question on Hangouts yesterday, but I've realised that it's no longer a good idea for me to chat there when I have no idea nor indication if you (THEtomaso) actually receive the messages or not, given the chat client you're using.. As such, I've now deleted Hangouts from my phone.

`#1468` seems like a more international matter, but I'll take care of `#1469`.

**Comment by THEtomaso** [comment]
> It seems to be complete bingo if Fanboy takes 4 hours or 4 months to fix reports.

If ever.

--

> `#1468` seems like a more international matter

`https://www.lampegiganten.dk/` and `https://www.lampegiganten.no/` are amongst the affected sites.

--

> I'll take care of `#1469`.

:+1:

**Comment by THEtomaso** [comment]
@lassekongo83:
More blocked article images:
`https://www.aftenposten.no/oslo/i/JJ8ya6/`
Same problem rule.
