### ISSUE TITLE
DailyCaller.com - Login broken (Frellwit's Swedish Filter)

### ISSUE THREAD

**Issue by THEtomaso** [lassekongo83/Frellwits-filter-lists#108]
### Affected site:
`https://dailycaller.com/`

### Issue:
Login is blocked.

### How to reproduce:
Click on the "LOG IN" button (in the top right corner).
Result: nothing happens!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **Frellwit's Swedish Filter**

### Problem rule:
`||experience.tinypass.com^*/execute$xmlhttprequest,domain=~auto-swiat.pl|~samharris.org`

### Possible fix:
```
- ||experience.tinypass.com^*/execute$xmlhttprequest,domain=~auto-swiat.pl|~samharris.org

+ ||experience.tinypass.com^*/execute$xmlhttprequest,domain=~auto-swiat.pl|~dailycaller.com|~samharris.org
```

### Temporary fix:
`@@||experience.tinypass.com^*/execute$xmlhttprequest,domain=dailycaller.com`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v29.1.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.28 (XUL)

**Comment by THEtomaso** [comment]
@DandelionSprout:
Your '**Browse websites without logging in**' list breaks the login function at a large number of sites, because of its TinyPass rule.
..but I suppose this should be considered expected behaviour, when using that specific filter?

**Comment by DandelionSprout** [comment]
`Daily Caller` is not a site I usually want to deal with, but since this is the 2nd `Tinypass`-related problem I've been told about in the past few weeks, I'll think about the matter much more closely.

Someone should probably also tell https://github.com/llacb47/miscfilters/blob/master/antipaywall.txt about this and https://github.com/DandelionSprout/adfilt/issues/173, then.

**Comment by THEtomaso** [comment]
> this is the 2nd `Tinypass`-related problem I've been told about in the past week

I just updated my own list..
Turns out that I had TinyPass unbreak rules in place for BWWLI for these sites too:
`financialpost.com`, `nationalpost.com`, `theprovince.com`, `torontosun.com`
..and those just happened to be the ones that I had bothered to fix.
