### ISSUE TITLE
Blocks images on idownloadblog.com

### ISSUE THREAD

**Issue by SebastianRasch** [lassekongo83/Frellwits-filter-lists#110]
For some reason, this filter blocks all images on idownloadblog on Mobile Safari/iOS. Works fine on desktop. 

Link: [idownloadblog.com](`https://www.idownloadblog.com`)

**Comment by lassekongo83** [comment]
I guess this fixes the issue as I have no Apple device to test with. I could only find one filter which I added an exception for.
