### ISSUE TITLE
Aftonbladet.se

### ISSUE THREAD

**Issue by mrjanston** [lassekongo83/Frellwits-filter-lists#111]
### Länk till sida

`Länk: [www.aftonbladet.se]`

### Beskriv problemet
All brödtext blockeras i artiklar. 

### Versioner

- Webbläsare/version: [Firefox 89.1.1 Mobile]
- uBlock Origin version: [1.35.2]

### Inställningar
Använder originalinställningar.

**Comment by davidhedlund** [comment]
Regel för att blockera Aftonbladet Plus banner som dyker upp  på huvudsidan:
> www.aftonbladet.se##.css-1mlmkwb
