### ISSUE TITLE
Aftonbladets nyhetsflöde fungerar inte

### ISSUE THREAD

**Issue by mjunix** [lassekongo83/Frellwits-filter-lists#112]
### Länk till sidan

`Länk: https://www.aftonbladet.se/nyheter/a/3Jgxj9/senaste-nytt-om-coronaviruset`

### Beskriv problemet
Nyhetsflödet som uppdateras live visas inte alls med "Frellwit's Swedish Filter" påslaget.

### Versioner

- Webbläsare/version: [Firefox 89.0.1 (64-bitars), Windows 10]
- uBlock Origin version: [uBlock Origin v1.35.2]

**Comment by lassekongo83** [comment]
Jag fixade detta för ett par dagar sedan. Prova med att forcera en uppdatering av listan. uBO inställningar > Filterlistor > Klicka på klockan bredvid `SWE: Frellwit's Swedish Filter` och klicka sen på knappen uppdatera nu.
