### ISSUE TITLE
hbl.fi

### ISSUE THREAD

**Issue by DandelionSprout** [lassekongo83/Frellwits-filter-lists#114]
### Länk till sidan

`Länk: https://www.hbl.fi/`

### Beskriv problemet

4 sponsede artikler på forsiden, med kun lave mengder leseverdi. Jeg foreslår `hbl.fi##.type-advertorial`

### Skärmdump(ar)

![image](https://user-images.githubusercontent.com/22780683/124708737-f6477300-defa-11eb-9989-bccb1c331b2d.png)

### Versioner

- Webbläsare/version: Chrome 91.0.4472.124 x64
- uBlock Origin version: 1.36.1b2 + IDCAC 3.3.1

### Inställningar

![image](https://user-images.githubusercontent.com/22780683/124708884-2727a800-defb-11eb-8856-d0684c54e2e7.png)

**Comment by lassekongo83** [comment]
Finns redan https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Frellwits-Swedish-Filter.txt#L1271

**Comment by DandelionSprout** [comment]
Ah, okei. Jeg glemte tydeligvis å skru på noen som helst svensk liste den siste uken, viste det seg... 😅 Min feil.
