### ISSUE TITLE
arkenzoo.se

### ISSUE THREAD

**Issue by Mik-pe** [lassekongo83/Frellwits-filter-lists#116]
### Länk till sidan

`Länk: https://www.arkenzoo.se/`

### Beskriv problemet
Det verkar som att cookie_content döljer en meny som dessutom gör att sidan inte går att använda (scrolla igenom). Sidan blir grå och går inte att använda.

### Skärmdump(ar)
![bild](https://user-images.githubusercontent.com/5653426/128872469-d93a07c6-6b6c-407d-9a4f-14ee0555a2df.png)

### Versioner

- Webbläsare/version: Firefox 90.0.2
- uBlock Origin version: uBlock Origin 1.37.2

**Comment by davidrmusti** [comment]
Det här påverkar också vetzoo.se, animail.se, mustijamirri.fi och petenkoiratavike.fi (de finska sajterna används också av svensktalande i Finland). Alla sajter skulle behöva samma fix för att kunna använda dem. @lassekongo83
