### ISSUE TITLE
sweclockers.com: anti-adblock messsage

### ISSUE THREAD

**Issue by wallrik** [lassekongo83/Frellwits-filter-lists#123]
### URL(s) where the issue occurs

`https://www.sweclockers.com/`

### Describe the issue

Anti-adblock message appears at the top of the page. Luckily, they were kind enough to give the element a unique id (`adblockBanner`).

### Screenshot(s)

![image](https://user-images.githubusercontent.com/10890923/155861869-030a4d73-4411-42cf-b311-15b5953ae722.png)

### Versions

- Browser/version: Firefox 97.0.1
- uBlock Origin version: uBlock Origin 1.41.8

**Comment by lassekongo83** [comment]
Are you using more than one adblocker? Updated the list?
