### ISSUE TITLE
foretagande.se

### ISSUE THREAD

**Issue by Sopor** [lassekongo83/Frellwits-filter-lists#124]
### URL(s) where the issue occurs

`Link: https://foretagande.se/nu-blir-det-billigare-att-starta-ett-aktiebolag-endast-25000kr`

### Describe the issue
When i have `Frellwit's Swedish Filter` enable this page will only show the footer of the page.

### Screenshot(s)
`Frellwit's Swedish Filter` enabled:
![image](https://user-images.githubusercontent.com/5789283/156048269-b77fd08a-b346-44f9-900a-25e392a134ae.png)

`Frellwit's Swedish Filter` disabled:
![image](https://user-images.githubusercontent.com/5789283/156048473-aed198ca-78e4-4079-8363-882718a610a2.png)

### Versions

- Browser/version: Firefox 97.0.1
- uBlock Origin version: 1.41.8

### Settings
uBO original setting except when i have `Frellwit's Swedish Filter` enabled of course 😊

**Comment by lassekongo83** [comment]
The article is a sponsored ad. So I don't see why it shouldn't be hidden. However, the links to that article should also be hidden, unless they somehow forgot to mark the article link as sponsored.
