### ISSUE TITLE
ionity.eu

### ISSUE THREAD

**Issue by PatrikElfstrom** [lassekongo83/Frellwits-filter-lists#133]
### URL(s) where the issue occurs

`Link: https://ionity.eu`

### Describe the issue

Cookie consent overlay is blocking site

### Versions

- Browser/version: FireFox 100
- uBlock Origin version: 1.42.4

### Settings

<img width="450" alt="image" src="https://user-images.githubusercontent.com/498356/157748702-8c06e5e8-531a-49fc-a337-0502bf0d815b.png">

**Comment by lassekongo83** [comment]
Not a Swedish website. And the problem is with Fanboy's Annoyance filter. Report to https://forums.lanik.us/
