### ISSUE TITLE
Flashback reklam

### ISSUE THREAD

**Issue by deroverda** [lassekongo83/Frellwits-filter-lists#134]
Länk: `https://www.flashback.org/t3415769`

På denna sida finns exempelvis reklam för gambling, som `https://record.epic.partners/_G2hBStld8rgr8Syj4RJS-mNd7ZgqdRLk/11/`

### Beskriv problemet

Problemet är att ingen reklam på Flashback är blockerad, men på de flesta andra svenska sidor är den det. Varför? 

### Versioner

- Webbläsare/version: [Firefox]
- uBlock Origin version: [Senaste]

### Inställningar

Default + Frellwits filter

**Comment by lassekongo83** [comment]
Ser ingen reklam. Du har inte råkat vitlista något? Kolla i uBO inställningar > Pålitliga webbplatser.

**Comment by deroverda** [comment]
> Ser ingen reklam. Du har inte råkat vitlista något? Kolla i uBO inställningar > Pålitliga webbplatser.

Du har rätt. User-noob-error från min sida. Tack.
