### ISSUE TITLE
aftonbladet.se: V75

### ISSUE THREAD

**Issue by davidhedlund** [lassekongo83/Frellwits-filter-lists#14]
### URL(s) where the issue occurs

aftonbladet.se

### Describe the issue

The V75 success stories are V75 ads.

### Screenshot(s)

![screenshot from 2018-03-25 18 03 55](https://user-images.githubusercontent.com/6416073/37877149-e7eb1f10-3056-11e8-9065-ffe3ed0079ce.png)

**Comment by davidhedlund** [comment]
Hmm, I'm not sure if it's possible to block them because they publish these "teasers" as "sport".

**Comment by lassekongo83** [comment]
Eftersom den inte är märkt som reklam så är det ett gränsfall. Har inga bevis på att Aftonbladet har fått betalt för att skriva denna artikeln. Man kan diskutera om att hela trav-delen är reklam egentligen. Så  det är inget som kommer att läggas till i listan just nu. Om du vill plocka bort alla travartiklar så kan du lägga till: `aftonbladet.se##a[href^="/sportbladet/trav365"]` som ett eget filter.

**Comment by davidhedlund** [comment]
> Om du vill plocka bort alla travartiklar så kan du lägga till: aftonbladet.se##a[href^="/sportbladet/trav365"] som ett eget filter.

Det var generöst av dig. Tack.
