### ISSUE TITLE
AB banner

### ISSUE THREAD

**Issue by H2SO4JB** [lassekongo83/Frellwits-filter-lists#142]
Hej Mattias,
Se bifogad bild. Har du möjlighet att blocka den stora bannern i nederkant som AB uppfann för
några dagar sedan som alltid visas vid en fräsch inladdning av sidan? I så fall, tack på förhand.

![AB](https://user-images.githubusercontent.com/13471707/189643769-58b42903-5950-440f-a9e6-ef056793d9dd.png)

**Comment by lassekongo83** [comment]
Det är ne temporär kampanj, så inget jag tänker lägga till i filtret. Men du kan själv använda denna: `aftonbladet.se##a[href^="https://payment."]:has-text(TESTA NU):upward(3)`

**Comment by H2SO4JB** [comment]
Jaha, okej. Ditt filter funkar perfekt. Tack för hjälpen. 👍🏻

**Comment by H2SO4JB** [comment]
Tack så mycket! Då håller vi tummarna att den här lösningen håller i sig framöver.  :-)

**Comment by H2SO4JB** [comment]
Hej igen Mattias,
Då var det dags igen för en ny banner i nederkant som kringgår ditt filter. Se bifogad skärmdump.
Ditt filter verkar istället ta bort stängknappen (krysset). Kan du kika på detta igen och kanske
hitta en bättre lösning som fixar dessa påtvingade banners som täcker 1/3 av skärmen?
Och som vanligt, tack på förhand.

![jghjgh9](https://user-images.githubusercontent.com/13471707/193453243-e630c5c2-eb5a-44d7-9f5f-4b5e2eff271d.png)

**Comment by H2SO4JB** [comment]
Som vanligt, supertack! 😃
