### ISSUE TITLE
aftonbladet.se: Wellobe banner

### ISSUE THREAD

**Issue by davidhedlund** [lassekongo83/Frellwits-filter-lists#143]
### Länk till sidan
[aftonbladet.se](https://www.aftonbladet.se/l)

### Beskriv problemet

Wellobe banner

### Skärmdump(ar)

![image](https://user-images.githubusercontent.com/6416073/190925097-ddc0cde9-1b97-46cb-9a5f-c444e113e152.png)

### Versioner

- Webbläsare/version: Firefox 104.0.2 64-bit for GNU/Linux
- uBlock Origin version: 1.44.2

### Inställningar

Inga, enbart installerat ditt filter.

**Comment by davidhedlund** [comment]
Snyggt! Tack så jättemycket.

**Comment by davidhedlund** [comment]
Den spökar forfarande. Wellobe bannern blinkar.

`<div class="hyperion-css-1ydvjup" hj6aocvjg="" yiigmu717=""><div class="hyperion-css-iblow6"><div class="hyperion-css-anrpup"><img src="https://arke-images.aftonbladet.se/logga-foldup.jpg" alt="" class="hyperion-css-90lm4q"></div><div class="hyperion-css-1re4xko"><div class="hyperion-css-1a89iqg">Investera i din hälsa!</div><div class="hyperion-css-cgc1io">Du får loggbok, kaloriberäknade recept och träningsprogram. JUST NU: 50% rabatt i 6 månader*</div><div class="hyperion-css-428apx"><a href="https://wellobe.aftonbladet.se/kampanj/blimedlem?utm_source=aftonbladet&amp;utm_medium=foldup" class="hyperion-css-1u89cs9">Bli medlem idag</a></div><div class="hyperion-css-kmmcqy">*Erbjudandet gäller vid tecknande av 6 månaders medlemskap t.o.m. 31 december 2022.</div></div><div><button type="button" class="hyperion-css-w3nhv5"><img src="/cnp-assets/closeButton.a3af1287.svg" alt="Stäng"></button></div></div></div>`

**Comment by lassekongo83** [comment]
Att den blinkar till är helt normalt eftersom jag måste använda mig av ett långsammare filter för att ta bort den.

**Comment by davidhedlund** [comment]
🎊

**Comment by davidhedlund** [comment]
> Att den blinkar en gång är helt normalt eftersom jag måste använda mig av ett långsammare filter för att ta bort den.

Den blinkar hela tiden vi vissa lägen.

**Comment by lassekongo83** [comment]
Det är möjligt att det går att skriva ett bättre filter, men den bannern syns inte så ofta för mig, trots att jag rensar alla kakor och cache vid nedstängning.
