### ISSUE TITLE
svt.se

### ISSUE THREAD

**Issue by Coada** [lassekongo83/Frellwits-filter-lists#148]
### Länk till sidan

`Länk: svt.se`

### Beskriv problemet
Cookie-popup lägger sig över sidan, förhindrar scroll

### Skärmdump(ar)

![svt](https://user-images.githubusercontent.com/7301477/210346343-e0cc1f17-8aa7-48b6-8112-1f464b543ed9.png)

### Versioner

- Webbläsare/version: Chrome 108.0.5359.125
- uBlock Origin version: uBlock Origin 1.46.0

**Comment by lassekongo83** [comment]
Den går inte att blockera utan att sidan går sönder tyvärr. Om du vill ha scroll: `svt.se##.nyh_cookie-consent:style(overflow:unset!important)`
