### ISSUE TITLE
api.gameanalytics.com

### ISSUE THREAD

**Issue by deroverda** [lassekongo83/Frellwits-filter-lists#156]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/Frellwits-filter-lists/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [ ] I've tried to reproduce the issue with uBlock Origin as the only browser extension activated.
- [ ] I've tried to reproduce the issue with uBlock Origin's default settings.

### The incorrectly removed content **does NOT**... (Leave blank if you do not know.)

- [ ] display ads.
- [ ] track the the user in any way. (This also include anonymous tracking.)
- [ ] interrupts or annoy the user. (Modal popups for example.)

### Description

Hi. Just got a quick question. I notice of all my block lists this is the only one that blocks "api.gameanalytics.com". I checked my analytics and it has blocked this domain 2500+ times in the last 6 hours. I wonder what game or service is making this request. Is it safe to keep it blocked? I've had some stuttering issues/high ping with Discord but maybe this has nothing to do with that. I'm pretty new to all of this so this might be a noobie question. sorry about that and thanks for your work. 

BTW, I'm using NextDNS with your list activated. 

### URL(s) where the issue occurs.

no specific URL. 

### Screenshot(s)

![firefox_38xpp0jcPV](https://user-images.githubusercontent.com/70813982/222928103-83358485-8892-4353-bd4a-fbcdffd3ab9b.png)

### Adblocker used and version

NextDNS 

### Browser name and version

Ublock Origin latest version.

**Comment by lassekongo83** [comment]
It should be safe to block. Gameanalytics is used to track and collect telemetry about various games. See if you play any games from the following developers: `https://gameanalytics.com/customers`
