### ISSUE TITLE
Det verkar som att TV4play har gjort förändringar ännu en gång.

### ISSUE THREAD

**Issue by orfeous1** [lassekongo83/Frellwits-filter-lists#158]
Det verkar som att TV4play har gjort förändringar ännu en gång.
Avsnitt som man har sett sparas inte.
Dessutom verkar det som om att det bli gula streck på själva tidslinjen och det blir småhack när man spelar ett avsnitt.

Reklam visas inte så det är ju bra.
Muspekaren är alltid synlig, den försvinner inte så jag måste dra den längst ut till höger så att den inte syns.
Vet inte om detta beror på ublock eller nåt annat?

Var snäll och kolla på detta.

Markerad som sedd blev fixad i ett annat inlägg jag gjorde förra året.

https://github.com/lassekongo83/Frellwits-filter-lists/issues/145

Men är som sagt tillbaka nu.

_Originally posted by @orfeous1 in https://github.com/lassekongo83/Frellwits-filter-lists/issues/152#issuecomment-1474886346_

**Comment by lassekongo83** [comment]
Problemen du beskriver om muspekare och avsnitt som inte sparas blir exakt samma om man stänger av uBO. Så felet måste ligga hos tv4. Några småhack har jag inte märkt av. De gula linjerna är harmlösa.

**Comment by orfeous1** [comment]
Okej, tack!
Jag får ge det lite tid och se om funktionen kommer tillbaka.
Det är lite störande att man inte kan se sedda avsnitt osv. Blir ibland svårt att hålla reda på vilka man sett och inte :)
Eventuellt får jag använda Kodi och retrospect med deras TV4. Var längesen jag kollade men brukade fungera väldigt bra där.

Jag meddelar igen om jag märker några förändringar på tv4play

**Comment by orfeous1** [comment]
Nu har TV4play fixat så att visade avsnitt fungerar igen.
Just nu är allt i sin ordning! :)

Men kan hända att dem gör något på sin sida som saker och ting slutar att fungera igen.
Jag återkommer om så blir fallet.
