### ISSUE TITLE
TV4 Play on Nvidia Shield and Adguard

### ISSUE THREAD

**Issue by kirilldem** [lassekongo83/Frellwits-filter-lists#162]
### Förutsättningar

- [X] Jag gjorde en [översiktlig sökning av problemspåraren](https://github.com/lassekongo83/Frellwits-filter-lists/issues?q=is%3Aissue) för att undvika att öppna en dubblett.
- [x] Jag försökte återskapa problemet när uBlock Origin är det enda aktiverade webbläsartillägget.
- [x] Jag försökte återskapa problemet när uBlock Origin använder standardlistor och inställningar.

### Beskrivning

Hello, 

I have been using the list for a while and it has been blocking ads on TV4 play android app. It seems that it doesnt do so anymore - I have checked that other ads are blocked using my adguard DNS server and they are blocked. Is there some work around or am I the only perosn who is facing this issue?

I checked expressen.se and there were no ads on shield running google chrome. 

Please let me know if there is some more logs I can share. 

### URL(er) där problemet uppstår.

tv4play app on android.

### Annonsblockerare och version

 AdGuard v0.107.24

### Webbläsare och version

Android 11

**Comment by lassekongo83** [comment]
Try blocking `videoplaza.tv` or `se-tv4.videoplaza.tv` in your DNS. If that doesn't work you need to watch in a browser with uBlock Origin.
