### ISSUE TITLE
TV4 videospelare

### ISSUE THREAD

**Issue by ealbwal1** [lassekongo83/Frellwits-filter-lists#163]
### Förutsättningar

- [X] Jag gjorde en [översiktlig sökning av problemspåraren](https://github.com/lassekongo83/Frellwits-filter-lists/issues?q=is%3Aissue) för att undvika att öppna en dubblett.
- [X] Jag försökte återskapa problemet när uBlock Origin är det enda aktiverade webbläsartillägget.
- [X] Jag försökte återskapa problemet när uBlock Origin använder standardlistor och inställningar.

### Det felaktigt borttagna innehållet gör **INTE** något av följande... (Lämna tomt om du inte vet.)

- [x] Visar annonser.
- [x] Spårar användaren på något sätt. (Detta inkluderar även anonym spårning.)
- [x] Avbryter eller irriterar användaren. (Modala popups till exempel.)

### Beskrivning

Kontrollerna för videospelaren på tv4 tas bort helt av filtret. Har provat att försöka fixa själv men verkar inte helt fungera. Ibland fungerar det i början men slutar efter där det skulle ha varit en reklampaus.

### URL(er) där problemet uppstår.

`https://www.tv4play.se/video/*`
Exempel: `https://www.tv4play.se/video/3baba7ba3b14cb321f53`

### Annonsblockerare och version

uBlock Origin 1.50.0

### Webbläsare och version

Firefox 114.0.2

**Comment by lassekongo83** [comment]
Lyckas inte återskapa problemet. Kontrollerna finns kvar även efter där det ska vara reklampaus för mig. Använder du några andra webbläsartillägg?

**Comment by ealbwal1** [comment]
Inga andra tillägg eller någonting sådant förutom de andra filter som följer med uBlock Origin, kan vara att det blir någon konflikt med någon av dem

**Comment by orfeous1** [comment]
Jag upplever också problem med TV4, ingen reklam visas. Däremot dyker bilden om reklam upp men återgår direkt efter till programmet man spelade upp. Problemet blir dock att det inte finns några kontroller för videospelaren. Går inte att välja helskärm eller fönsterläge. Ingen tidslinje eller nåt visas. Går inte att pausa. Videon spelas upp så man måste snällt sitta och titta tills den tar slut.

Detta hände för mig när TV4play lanserade deras nya sida.

**Comment by lassekongo83** [comment]
@orfeous1 Kan du när du tittar på en video klicka på [report knappen](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) (chat ikonen) > Scrolla längst ner till Felsökningsinformation och posta det här?

**Comment by orfeous1** [comment]
> @orfeous1 Kan du när du tittar på en video klicka på [report knappen](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) (chat ikonen) > Scrolla längst ner till Felsökningsinformation och posta det här?

Absolut!
Jag kan gå in på vilken video eller klipp som helst. Får samma resultat. Videospelaren försvinner. Tills att jag trycker på uppdatera då kommer den tillbaka och videon startar om eller startar ibland där ifrån jag valde att uppdatera sidan.

Här kommer felsökningsinformationen.

uBlock Origin: 1.51.1rc5
Chromium: 116
filterset (summary):
 network: 100655
 cosmetic: 42141
 scriptlet: 18797
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 15-0, never
  SWE-1: 4619-0, 14h.30m
  easylist: 70374-16, 14h.30m
  easyprivacy: 33208-68, 14h.30m
  plowe-0: 3723-1069, 14h.30m
  ublock-badware: 7955-146, 14h.30m
  ublock-filters: 34562-130, 14h.30m
  ublock-privacy: 545-6, 14h.30m
  ublock-quick-fixes: 302-71, 2h.30m
  ublock-unbreak: 2129-32, 14h.30m
  urlhaus-1: 5849-0, 14h.30m
filterset (user): [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 761 ms (selfie)
 maxAssetCacheWait: 351 ms
popupPanel:
 blocked: 18
 network:
  tv4play.se: 1
  bugsnag.com: 3
  imrworldwide.com: 2
  k5a.io: 1
  smartclip.net: 2
  videoplaza.tv: 4
  youborafds01.com: 5
 extended:
  ##button:has-text(Besök annonsör)
  ##.avod-web-player-pause:style(background-color:transparent!impo…

**Comment by orfeous1** [comment]
Här har du samma felsökningsinformation efter att jag har tryckt uppdatera sida på samma videoklipp med videospelaren synlig.

uBlock Origin: 1.51.1rc5
Chromium: 116
filterset (summary):
 network: 100655
 cosmetic: 42141
 scriptlet: 18797
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 15-0, never
  SWE-1: 4619-0, 14h.33m
  easylist: 70374-16, 14h.33m
  easyprivacy: 33208-68, 14h.33m
  plowe-0: 3723-1069, 14h.33m
  ublock-badware: 7955-146, 14h.33m
  ublock-filters: 34562-130, 14h.33m
  ublock-privacy: 545-6, 14h.33m
  ublock-quick-fixes: 302-71, 2h.33m
  ublock-unbreak: 2129-32, 14h.33m
  urlhaus-1: 5849-0, 14h.33m
filterset (user): [array of 15 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 761 ms (selfie)
 maxAssetCacheWait: 351 ms
popupPanel:
 blocked: 9
 network:
  tv4play.se: 1
  bugsnag.com: 1
  imrworldwide.com: 1
  smartclip.net: 1
  videoplaza.tv: 1
  youborafds01.com: 4
 extended:
  ##button:has-text(Besök annonsör)
  ##.avod-web-player-pause:style(background-color:transparent!impo…

**Comment by lassekongo83** [comment]
Jag kan inte se något utöver det normala. Har webbläsaren du använder inbyggd annonsblockering? I så fall prova med att slå av den. Prova även med att avaktivera alla andra webbläsartillägg.

**Comment by orfeous1** [comment]
> ### Förutsättningar
> * [x]  Jag gjorde en [översiktlig sökning av problemspåraren](https://github.com/lassekongo83/Frellwits-filter-lists/issues?q=is%3Aissue) för att undvika att öppna en dubblett.
> * [x]  Jag försökte återskapa problemet när uBlock Origin är det enda aktiverade webbläsartillägget.
> * [x]  Jag försökte återskapa problemet när uBlock Origin använder standardlistor och inställningar.
> 
> ### Det felaktigt borttagna innehållet gör **INTE** något av följande... (Lämna tomt om du inte vet.)
> * [x]  Visar annonser.
> * [x]  Spårar användaren på något sätt. (Detta inkluderar även anonym spårning.)
> * [x]  Avbryter eller irriterar användaren. (Modala popups till exempel.)
> 
> ### Beskrivning
> Kontrollerna för videospelaren på tv4 tas bort helt av filtret. Har provat att försöka fixa själv men verkar inte helt fungera. Ibland fungerar det i början men slutar efter där det skulle ha varit en reklampaus.
> 
> ### URL(er) där problemet uppstår.
> `https://www.tv4play.se/video/*` Exempel: `https://www.tv4play.se/video/3baba7ba3b14cb321f53`
> 
> ### Skärmdump(ar)
> _No response_
> 
> ### Annonsblockerare och version
> uBlock Origin 1.50.0
> 
> ### Webbläsare och version
> Firefox 114.0.2

Det vore intressant att höra hur det går för dig då vi har samma problem och dessutom med olika webbläsare osv.

Mina problem började nu när TV4play gjorde om på sin sida. Har fungerat bra fram till dess.

@ealbwal1

**Comment by orfeous1** [comment]
> Jag kan inte se något utöver det normala. Har webbläsaren du använder inbyggd annonsblockering? I så fall prova med att slå av den. Prova även med att avaktivera alla andra webbläsartillägg.

Tack för att ni försöker.
Jag får helt enkelt lära mig att leva med problemet. Jag vet ju hur jag ska göra för att få tillbaka videospelaren eller vad man kallar det? Overlay?

Google Chrome använder nån typ av annonsblockering men det är inget som stör eller har stört förr.
De tillägg som är aktiverade är istort sett bara ublock och LastPass.

Stänger jag av ublock på TV4play så visas allting som det skall. Dock med reklam.

Jag ska testa att stänga av ett gäng filter i listan och se vad som händer.

**Comment by orfeous1** [comment]
Stängde av alla filter i filter listan förutom ert filter.
Det verkar som om det fungerar just nu.
Jag ska fortsätta att testa.

Jag håller er uppdaterade om vad som händer och inte.
