### ISSUE TITLE
Frellwit's Swedish Filter blocking Legitimate Aweber form's JavaScript code

### ISSUE THREAD

**Issue by SunilSuresh5260** [lassekongo83/Frellwits-filter-lists#167]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/Frellwits-filter-lists/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [ ] I've tried to reproduce the issue with uBlock Origin as the only browser extension activated.
- [ ] I've tried to reproduce the issue with uBlock Origin's default settings.

### The incorrectly removed content **does NOT**... (Leave blank if you do not know.)

- [X] display ads.
- [ ] track the the user in any way. (This also include anonymous tracking.)
- [X] interrupts or annoy the user. (Modal popups for example.)

### Description

Hi,

I have a Aweber form on some of my websites. I find that whenever I view the websites with AdGuard on, the form is not getting displayed. On further investigation, I now find that the JavaScript code of the form is being blocked by the Frellwit's Swedish Filter.

This is what your log file says:
Status: --- GET 3P
Filtering status: Blocked
URL: https://forms.aweber.com/form/55/1414290755.js
Open in a new tab
Type: JavaScript
Source: profitgenerationsecrets.com
Rule: ||aweber.com^$third-party
Filter: Frellwit's Swedish Filter

### URL(s) where the issue occurs.

`https://profitgenerationsecrets.com`

### Adblocker used and version

AdGuard Adblocker 4.1.56

### Browser name and version

Latest Google Chrome 114.0.5735.199 64-bit; it was also happening in earlier versions of Chrome

**Comment by lassekongo83** [comment]
I don't believe aweber is legitimate or is of any interest to any users that choose to block ads/marketing/tracking.

However, if you want to locally unblock it, then add `@@||forms.aweber.com/form/` to your filters.
