### ISSUE TITLE
Incorrectly blocked ressource

### ISSUE THREAD

**Issue by nata1993** [lassekongo83/Frellwits-filter-lists#174]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/Frellwits-filter-lists/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I've tried to reproduce the issue with uBlock Origin as the only browser extension activated.
- [X] I've tried to reproduce the issue with uBlock Origin's default settings.

### The incorrectly removed content **does NOT**... (Leave blank if you do not know.)

- [X] display ads.
- [X] track the the user in any way. (This also include anonymous tracking.)
- [X] interrupts or annoy the user. (Modal popups for example.)

### Description

Hello! 

I'm developing a web application tool for myself that would take CSV file as data input, work with the data, make some statistics out of the data, present the data and the statistics to the user and that's it. But apparently this uBlock Origin filter for some reason blocked one of the scripts I was using for handling statistics from the presented CSV data. Filter blocked a file that has only a class and a constructor within a file. Nothing else, just a class, constructor and variables for the constructor. File name is Statistics.js. My guess is  because of the name, the file was blocked from loading. Since I'm running builder pattern in this case and have StatisticsBuilder class and exactly same named file for the builder, it did not get blocked. Hence just a guess that it might be possibility that file was blocked from loading purely because it has a name Statistics. Better yet, all the data manipulation is done local host aka on the client side. No server side at all.

Error message is from console when filter was activated:
Loading failed for the <script> with source “https://nata1993.github.io/tarbimise_graafik/ObjectBuilder/StatisticsBuilder/Statistics/Statistics.js”.

![Project itself](https://github.com/nata1993/tarbimise_graafik)

### URL(s) where the issue occurs.

https://nata1993.github.io/tarbimise_graafik/

### Screenshot(s)

![Screenshot of file internals](https://github.com/lassekongo83/Frellwits-filter-lists/assets/6074645/8c1e6b94-f77f-43dc-8d3a-82e438b4a065)

### Adblocker used and version

1.51.0

### Browser name and version

FireFox 117.0 (64bit)

**Comment by lassekongo83** [comment]
If the web app is only for yourself you can add an exception filter in uBO settings > My filters. Add: `@@/statistics/statistics.js`
