### ISSUE TITLE
tv4play.se: Laddar

### ISSUE THREAD

**Issue by davidhedlund** [lassekongo83/Frellwits-filter-lists#18]
### URL(s) where the issue occurs

`https://www.tv4play.se/program/kalla-fakta/3955074`

### Describe the issue
Den animerade röda laddningsikonen slutar inte visa sig. Den visar sig inte med uBO av.

Tillfällig lösning är att hoppa fram i videon (höger pil) för att gömma laddningsikonen, och sedan hoppa tillbaks (vänster pil).

### Screenshot(s)

![screenshot from 2018-05-05 20 24 28](https://user-images.githubusercontent.com/6416073/39666339-5b2be02a-50a2-11e8-8ead-d7141fa0e3c1.png)

### Versions

- Browser/version: Firefox 59.02 (64-bit) for GNU/Linux
- uBlock Origin version: 1.16.4

### Settings

uBlock Origin: Default+Frellwits-filter-lists
Firefox: DMR är aktiverat (Widevine Content Decryption Module provided by Google Inc.)

**Comment by davidhedlund** [comment]
![screenshot from 2018-05-05 20 33 46](https://user-images.githubusercontent.com/6416073/39666424-c7a5cd6e-50a3-11e8-8c70-32a1ae3ae09f.png)

Förresten, detta filter måste läggas till för att visa bilden i normal kontrast:
> tv4play.se###skin-cover

![screenshot from 2018-05-05 20 34 18](https://user-images.githubusercontent.com/6416073/39666427-ccbf831c-50a3-11e8-87a5-67a070b13d5d.png)

**Comment by lassekongo83** [comment]
Prova `tv4play.se##script:inject(addEventListener-defuser.js, load, ())` ett tag och se om inget annat slutar att fungera. För mig verkar allt fungera bra än så länge.

**Comment by davidhedlund** [comment]
> Prova tv4play.se##script:inject(addEventListener-defuser.js, load, ())

Tack så mycket, det tog bort det direkt. Vänligen lägg till en commit länk här om du lägger till det.

**Comment by davidhedlund** [comment]
Kan du lägga till
> tv4play.se###skin-cover

See https://github.com/lassekongo83/Frellwits-filter-lists/issues/18#issuecomment-386826358

**Comment by davidhedlund** [comment]
Respekt.

**Comment by davidhedlund** [comment]
Jag får detta meddelande i Firefox när jag spelar filmer, även om jag använder en helt ny profil

> Uppspelning stöds inte officiellt i denna browser.

Trots att https://www.tv4play.se/support#humany-tv4play=/496-vad-aer-systemkraven-foer-tv4-play nämner "Firefox". Kan du testa detta? Visst borde jag rapportera detta till TV4?

**Comment by lassekongo83** [comment]
Har märkt att det sker när man kör Linux. Bara till att ignorera och plocka bort med ett kosmetiskt filter som jag nyss gjorde. :)

**Comment by davidhedlund** [comment]
Men då försvinner ju meddelandet i webbläsare som faktiskt inte har stöd. Är det inte bättre om jag rapporterar detta till TV4?

**Comment by lassekongo83** [comment]
Om webbläsaren inte har stöd så kan den nog inte köra uBlock Origin. :)

**Comment by davidhedlund** [comment]
Har uBO stöd för alla webläsare som anges i https://www.tv4play.se/support#humany-tv4play=/496-vad-aer-systemkraven-foer-tv4-play?: Chrome, Firefox, Safari, Microsoft Edge

Vad händer om stödet ändras?

Jag har rapporterat problemet till TV4 nu.

**Comment by davidhedlund** [comment]
Tack för alla filter. Nu går det se Kalla Fakta utan några problem.

**Comment by lassekongo83** [comment]
Det är ett felmeddelande som dyker upp när man blockerar reklamen har jag märkt. Delade du med dig av den informationen så ser väl Bonnier rött just nu. ;P

**Comment by davidhedlund** [comment]
Jag får samma felmeddelande även i en helt ny profil (uBO är ej installerat). Testa själv.

**Comment by lassekongo83** [comment]
Jag gissar på att Bonnier inte testar sina HTML5 spelare i GNU/Linux miljö. Så det är därför det lägger till meddelandet där för säkerhets skull. Hände väl mig för några veckor sedan på `tv4.se` när jag skulle testa ett klipp i Chromium. Spelaren ville inte spela upp klippet, men det fixade jag snabbt när jag bytte user agent till Chrome/Windows under network conditions i Chromium.

**Comment by davidhedlund** [comment]
Jag tror du har rätt i den saken. Förhoppningsvis kommer de utreda detta nu.
