### ISSUE TITLE
Request: Tyda.se annoying ads not being blocked

### ISSUE THREAD

**Issue by orfeous1** [lassekongo83/Frellwits-filter-lists#185]
Jag önskar att all reklam och annonser försvann från tyda.se
Jag har testat att manuellt blockera med ublocks "elementväljarläge" flera gånger men de kommer tillbaka
varje gång jag uppdaterar sidan. Annonserna osv verkar generera nya id's varje gång.

Detta är ett önskemål från mig

**Comment by lassekongo83** [comment]
Vilka annonser? Jag ser inga alls.

1. Gör en backup och [återställning](https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#backuprestore-section) av uBOs inställningar.
2. Avaktivera andra webbläsartillägg. Andra webbläsartillägg kan skapa konflikter med uBO.
3. Fortfarande annonser? Posta en skärmdump, skriv vilken webbläsare du använder, och annat som kan tänkas vara bra att veta.

**Comment by orfeous1** [comment]
Jag fick till det genom att lägga till dessa regler under "Mina regler" i ublock.
efter detta så blev jag av med alla videoklipp som visades.

tyda.se showheroes.com * block
tyda.se youplay.se * block

**Comment by lassekongo83** [comment]
Youplays videos må vara störande och fullständigt orelaterat till innehållet, men de är inga annonser.
