### ISSUE TITLE
Generell underhållning

### ISSUE THREAD

**Issue by davidhedlund** [lassekongo83/Frellwits-filter-lists#19]
Problem som inte är avklarade är markerade med texted "todo" i detta dokument. Vänligen låt detta problem vara öppet även om det kommer ta lång tid att fixa.

# Migrera icke-Svenska filter
[ursprungligen från [https://github.com/lassekongo83/Frellwits-filter-lists/commit/774e746da3ef2e71b28363c7f54c6db257ee868a](https://github.com/lassekongo83/Frellwits-filter-lists/commit/774e746da3ef2e71b28363c7f54c6db257ee868a)]

Icke-Svenska filter som passar i uBO standard filter som tex EasyList och EasyPrivacy bör migreras. Visst är det jobbigare men du sprider filtrena på rätt sätt, och de får fler användare.

Jag föreslår att du migrerar dem periodvis, det kanske gör denna arbetsuppgift rimmlig.

Likaväl anser jag att folk borde migrera Svenska EasyList och EasyPrivacy filter till ditt filter.

# Döda domäner

Jag har glömt av vad tex EasyList (och du) gör med domäner som gått ut. Brukar de ta bort dem från listan?

Om du vill kan jag göra ett skript för att sålla ut gammla domäner i https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Frellwits-Swedish-Filter.txt och rapportera dem till dig.

Exempel: adaptlogic.com

**Comment by lassekongo83** [comment]
> Likaväl anser jag att folk borde migrera Svenska EasyList och EasyPrivacy filter till ditt filter.

Min lista är enbart skriven för uBlock Origin. EasyList och EasyPrivacy används av väldigt många andra annonsblockerare.

**Comment by davidhedlund** [comment]
> Nu rapporterade du ju för det mesta enbart till de som har dessa regionala listor aktiverade vilket inte är alla. Jag tror majoriteten av svenskarna enbart har standard-inställningarna när de installerar uBO. Så jag ser ingen bra anledning med att ta bort de flesta av dessa eftersom då blir alla svenskar utsatta för dessa domäner.

Då är ditt filter inte längre regionalt, utan flerspråkigt. Kan du vara snäll och lägga till någon text om att du lägger till populära filter till siter på andra språk än Svenska?

> Enbart de som läggs in i EasyList, EasyPrivacy eller Peter Lowe’s Ad and tracking server list kan jag tänka mig plocka bort.

Kommer du ta bort dessa filter?:
> ||mailerlite.com^$third-party
* EasyPrivacy: ||track.mailerlite.com^

> ||onesignal.com^$third-party
* Peter Lowe’s Ad: cdn.onesignal.com
* EasyList: @@||onesignal.com^$script,domain=_many sites_


https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Swedish/EXTRA_INFO.md säger
> Listan är testat tillsammans med uBlock Origins orginalinställningar. Då används dessa listor: EasyList, EasyPrivacy, Peter Lowe's Ad server list, Malware Domain List, Malware domains och uBlock Filters. Listan bör även fungera bra tillsammans med Fanboy's alla listor. Det finns dock alltid en liten möjlighet att vissa konflikter kan uppstå tillsammans med andra listor.

Kan även tänka dig ta bort filter som finns i **Malware Domain List, Malware domains och uBlock Filters**?


> (uBlockAdmin/uBlock har heller inget med uBlock Origin att göra. Det är ett scam repo.)

Jag tog bort den och rapporterade till deras Forum istället.

**Comment by lassekongo83** [comment]
> Då är ditt filter inte längre regionalt, utan flerspråkigt. Kan du vara snäll och lägga till någon text om att du lägger till populära filter till siter på andra språk än Svenska?

Egentligen är det ganska irrelevant då alla av dessa domäner som finns i listan förekommer (eller har förekommit) på svenska webbsidor också. Meningen är att dessa domäner inte ska kunna skicka förfrågningar när man surfar in på en svensk webbsida. Bonus om man är svensk och kikar in på någon utländsk webbsida som använder samma blockerade tjänster. Tror inte heller så många icke-svenskar använder listan förutom kanske några norska, finska och danska användare.

> EasyPrivacy: ||track.mailerlite.com^

Här får jag ta ett enskilt beslut. Behåller nog hela den domänen blockerad så länge eftersom de också sysslar med annat än spårning. (Som till exempel irriterande newsletter modal pop-ups.) Det är väl om nån viktig funktion försvinner nånstans som jag får modifiera eller ta bort den.

> onesignal.com

Kan jag möjligen ta bort ja. Får se om jag kan hitta sidan jag stötte på den på så jag vet om något annat  irriterande inte slinker förbi likt ovan.

> Kan du tänka dig att sortera listan så här?

Blir bara jobbigt att hålla reda på vilka domäner som hör till vilken grupp.

**Comment by davidhedlund** [comment]
> Egentligen är det ganska irrelevant då **alla av dessa domäner som finns i listan förekommer (eller har förekommit) på svenska webbsidor också. Meningen är att dessa domäner inte ska kunna skicka förfrågningar när man surfar in på en svensk webbsida. Bonus om man är svensk och kikar in på någon utländsk webbsida som använder samma blockerade tjänster.**

Kan du vara snäll och dokumentera detta i https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Swedish/EXTRA_INFO.md ?

**Comment by lassekongo83** [comment]
https://github.com/lassekongo83/Frellwits-filter-lists/commit/3cbe671f348e90c3ebd70d458138a606014f5196

**Comment by davidhedlund** [comment]
Tack så mycket.

**Comment by davidhedlund** [comment]
En annan sak som jag tycker borde läggas till i https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Swedish/EXTRA_INFO.md

> Listan är testat tillsammans med uBlock Origins orginalinställningar. Då används dessa listor: EasyList, EasyPrivacy, Peter Lowe's Ad server list, Malware Domain List, Malware domains och uBlock Filters.

Beskriv att du önskar att man rapporterar dubletter som finns i någon av uBOs standardfilter och din filterlista så att du kan ta bort dem.

**Comment by davidhedlund** [comment]
Vad tycker du om mitt förslag?

**Comment by lassekongo83** [comment]
https://github.com/lassekongo83/Frellwits-filter-lists/commit/c74c57781cba61186dfaf357c67b56561b934f10

**Comment by davidhedlund** [comment]
Schysst.

**Comment by davidhedlund** [comment]
# gigya.com

Frellwits:

> ||gigya.com^$third-party,domain=~pgatour.com

pgatour.com är inte en svensk sida.


EasyPrivacy:

> ||counters.gigya.com^
> ||gigya.com^*/cimp.gif?
> ||gigya.com/js/gigyaGAIntegration.js

**Comment by davidhedlund** [comment]
Jag lade till texten "todo" på två ställen på den här sidan.

**Comment by davidhedlund** [comment]
# Todo: Högtraffikerade domäner

> pushcrew.com
> platform.linkedin.com
> meltwater.com
> intercom.io
> createsend.com
> cision.com

Var föreslår du att jag rapporterar dem?

**Comment by lassekongo83** [comment]
> ~pgatour.com

`~` innebär undantag på grund av #15.

Det är ingen idé att rapportera dessa domäner så länge du inte har något exempel på vart de förekommer. Det krävs nämligen. Tyvärr så minns jag inte heller längre var jag hittade dessa. 

Några kanske redan finns i `Fanboy's Annoyance filter` också. Men eftersom den inte är inkluderad i standardinställningarna, och att jag även har ett liknande mål som den listan, så gör det inget om `FB Annoyance/cookie` och till viss del `social filter` och denna listan har dubbletter.

**Comment by davidhedlund** [comment]
> Det är ingen idé att rapportera dessa domäner så länge du inte har något exempel på vart de förekommer. Det krävs nämligen. Tyvärr så minns jag inte heller längre var jag hittade dessa.

Hur gör brukar du göra för att lista ut var de förekommer? Kan man inte använda något i stil med detta?:
> site:pushcrew.com

**Comment by lassekongo83** [comment]
> site:pushcrew.com

Kommer enbart att söka inom den domänen och inte på domäner som använder sig av den. 
Tjänsten `https://publicwww.com` finns, men den är inte gratis hela tiden.

**Comment by davidhedlund** [comment]
Off-topic men behöver lite hjälp: Videoklipp på aftonbladet.se och expressen.se startar med utan volym (mute). Det är drygt att behöva klicka på volymikonerna varje gång för att få ljud. Jag har det här problemet i en helt ny profil i Firefox 60.0 (64-bit) för GNU/Linux men hade det även i 59.0.2. Jag vet inte hur jag ska felsöka vidare. Du som är kunnig, kan du komma med tips?

**Comment by davidhedlund** [comment]
Jag mailade både AB och Expressen för att höra vad som försigår. Jag återkommer till dig så du får ta del av svaret.
