### ISSUE TITLE
Enable 

### ISSUE THREAD

**Issue by forthrin** [lassekongo83/Frellwits-filter-lists#192]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/Frellwits-filter-lists/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I use no other ad blockers or privacy blocking tools/extensions other than my preferred one.
- [X] I've tried to reproduce the issue with uBlock Origin as the only browser extension activated.
- [X] I've tried to reproduce the issue with uBlock Origin's default settings.

### Description

Referring to the similar #148, this removes dialog and opacity for the streaming site, but mouse events are disabled.

```
www.svtplay.se###__next div[role=main]
www.svtplay.se##.hiwxxe
```

How does one re-enable mouse events (or prevent disabling in the first place)? Assuming Greasemonkey must be used.

(I was surprised to find no Extensions for this, only for enabling the right mouse button.)

### URL(s) where the issue occurs.

https://www.svtplay.se/

### Adblocker used and version

uBlock Origin 1.56.0

### Browser name and version

Firefox 123

**Comment by lassekongo83** [comment]
If you have `trustedListPrefixes ublock- user-` set in [advanced settings](https://github.com/gorhill/uBlock/wiki/Advanced-settings), then: `svtplay.se##+js(trusted-set-cookie, cookie-consent-1, {"optedIn":true\,"functionality":true\,"statistics":false})` should get rid of the cookie popup and enable all functionality.

**Comment by forthrin** [comment]
![Thanks](https://github.com/lassekongo83/Frellwits-filter-lists/assets/1167421/3001833f-d22a-4471-bea9-6114707bbbbc)

**Comment by forthrin** [comment]
Tried to use this new-found knowledge to avoid the annoying "choose country" pop-up on this site (which even moronically redirects to the root document afterwards no matter what you choose). How can the rule be changed to work as intended?

https://www.oxo.com/joe-chop-and-spin-bundle.html

`www.oxo.com##+js(trusted-set-cookie, geo_location, "US", 1year, reload)`

**Comment by forthrin** [comment]
@lassekongo83: uBlock Origin suddenly started complaining about "not trusted source", so the webpage is not clickable. Tried adding `-user` to `trustedListPrefixes` to no avail. What is the proper fix for making the webpage clickable again?

**Comment by lassekongo83** [comment]
Are the 2 checkboxes at the top in "My Filters" page checked? If not, make sure they are.

For svtplay you may also need to update to the dev build of uBO and add: `svtplay.se##+js(trusted-set-cookie, cookie-consent-1, '{"optedIn":true,"functionality":true,"statistics":false}')` (Won't work in version 1.57.2).

As for the oxo site. Looks like the site is redirected on the server side which runs before uBO can set cookies. You can prevent the website from redirecting you, but it may cause breakage. Use at your own risk: `oxo.com##^responseheader(location)`

**Comment by forthrin** [comment]
Both suggestions seem to work perfectly. Thank you so much again!

PS! Can you explain quickly the "trusted sources"? Must all filters be registered verbatim in a central database?

**Comment by lassekongo83** [comment]
It's just a prefix setting, only uBO filters are trusted by default. https://github.com/gorhill/uBlock/wiki/Advanced-settings#trustedlistprefixes

**Comment by forthrin** [comment]
Not completely clear. One can add "My filters" without changing any default settings, but with JS stuff like this, some kind of check is evidently performed (against an online server...?) So what exactly is checked? Is it something like, eg. pseudo:

```
the_whole_thing = "svtplay.se##+js(trusted-set-cookie, cookie-consent-1, '{"optedIn":true,"functionality":true,"statistics":false}')"
unless lookup(the_whole_thing, "https://...ublock.../trusted-rules").status == 'safe' then warn user
```

**Comment by lassekongo83** [comment]
uBO does not connect to any servers unless filters/scriptlets are updated. Trusted filters are checked within the extension locally. You can probably see how it's done in the source code: https://github.com/gorhill/uBlock/tree/master

Probably somewhere in [1p-filters.js](https://github.com/gorhill/uBlock/blob/master/src/js/1p-filters.js) and [scriptlets.js](https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js).

**Comment by forthrin** [comment]
@lassekongo83: nytimes.com started blocking (link) click events (related to modal boxes). Is there a generic catch-all/most way to revert sites from blocking default click events for <a> tags, which is universally unwanted?

**Comment by lassekongo83** [comment]
For nytimes you'll need:

```
/fides$domain=nytimes.com
nytimes.com###complianceOverlay
nytimes.com##body:style(overflow:unset!important;)
nytimes.com###app[inert]:remove-attr(inert)
```

The inert attribute is preventing clicks there. There is no generic catch-all as every website is different.

**Comment by forthrin** [comment]
WFM! Thanks a lot!

Assuming inert is a a site-specific attribute that is searched for by a script that overwrites click events for said tag.

What method are you using to track down the event meddling for a given site (and the simplest intervention to bypass it)?

(Trying to click the "event" box in Inspector seems futile as it lists hundreds of events.)

**Comment by lassekongo83** [comment]
To track pesky click annoyances I:

1. Check the uBO logger for any obvious network requests. If some script is named `modal`, `popup`, `copy-protection`, `cookie-compliance` or similar I try to block it.
2. Check the website's CSS in the browser dev tools for any properties that prevents clicking or copying etc. For example: `pointer-events: none;`
3. Check the html for attributes or invisible elements that may overlay the content.
4. Uncheck some event listeners related to mouse events.

**Comment by forthrin** [comment]
Once again, the site has changed. Unable to figure out what to do using your 1-4 list. Little help?

1. Blocking the following URL causes "Application error: a client-side exception has occurred".

https://australis.svtplay.se/bucket/play7/_next/static/chunks/CookieConsentView.26d4fd9eafaab31b.js

2. The following rule is not trusted by uBlock anymore.

svtplay.se##+js(trusted-set-cookie, cookie-consent-1, '{"optedIn":true,"functionality":true,"statistics":false}')

3. No mention of `svtplay` in the uBlock issue tracker.
4. The uBlock source tree contains no references to `svt` at all.
