### ISSUE TITLE
TV4.se not working

### ISSUE THREAD

**Issue by robbah99** [lassekongo83/Frellwits-filter-lists#196]
### Förutsättningar

- [X] Jag gjorde en [översiktlig sökning av problemspåraren](https://github.com/lassekongo83/Frellwits-filter-lists/issues?q=is%3Aissue) för att undvika att öppna en dubblett.
- [X] Jag använder inga andra annonsblockerare eller sekretessblockeringsverktyg annat än den jag föredrar. (För att utesluta ogiltiga problem är det viktigt att endast använda en blockerare.)
- [X] Jag försökte återskapa problemet när uBlock Origin är det enda aktiverade webbläsartillägget.
- [X] Jag försökte återskapa problemet när uBlock Origin använder standardlistor och inställningar.

### Det felaktigt borttagna innehållet gör **INTE** något av följande... (Lämna tomt om du inte vet.)

- [ ] Visar annonser.
- [ ] Spårar användaren på något sätt. (Detta inkluderar även anonym spårning.)
- [ ] Avbryter eller irriterar användaren. (Modala popups till exempel.)

### Beskrivning

Cannot start tv programs. Play button is "dead"

### URL(er) där problemet uppstår.

`https://www.tv4play.se/video/95fd750e5067dc142119/avsnitt-15-granslandet`

### Annonsblockerare och version

ublock origin 1.57.2

### Webbläsare och version

124.0.2 (64-bit)

### Konfiguration

<details>
<summary>Detaljer</summary>

```yaml


```
</details>

**Comment by lassekongo83** [comment]
Nu bör det fungera igen, förutom att det inte syns någon seekbar. Ska kolla vad som är fel när jag har tid. Lämnar denna öppen så länge.
