### ISSUE TITLE
ul.se fungerar inte tillsammans med EasyList – Cookie Notices

### ISSUE THREAD

**Issue by wallrik** [lassekongo83/Frellwits-filter-lists#198]
### Förutsättningar

- [X] Jag gjorde en [översiktlig sökning av problemspåraren](https://github.com/lassekongo83/Frellwits-filter-lists/issues?q=is%3Aissue) för att undvika att öppna en dubblett.
- [X] Jag använder inga andra annonsblockerare eller sekretessblockeringsverktyg annat än den jag föredrar. (För att utesluta ogiltiga problem är det viktigt att endast använda en blockerare.)
- [ ] Jag försökte återskapa problemet när uBlock Origin är det enda aktiverade webbläsartillägget.
- [ ] Jag försökte återskapa problemet när uBlock Origin använder standardlistor och inställningar.

### Det felaktigt borttagna innehållet gör **INTE** något av följande... (Lämna tomt om du inte vet.)

- [ ] Visar annonser.
- [ ] Spårar användaren på något sätt. (Detta inkluderar även anonym spårning.)
- [ ] Avbryter eller irriterar användaren. (Modala popups till exempel.)

### Beskrivning

Oklart för mig om detta är något som kan fixas med hjälp av denna svenska filterlista, men `ul.se` kräver att man klickar på något i deras cookie-banner innan det går att använda sidan (söka resor).

Cookie-bannern blockeras av EasyList – Cookie Notices.

Vid snabb Google-sökning får jag sidan att fungera med detta:
```
ul.se#%#//scriptlet('set-cookie', 'ulse_atc', 'no')
```

Men förstår det som att enbart vissa listor får köra scriptlets?

Går det att komma runt problemet utan att sätta en cookie? Jag vet inte.

### URL(er) där problemet uppstår.

`https://www.ul.se/`

### Skärmdump(ar)

Denna suddiga bild visas istället för att reseplaneraren laddas
![nfpb](https://github.com/lassekongo83/Frellwits-filter-lists/assets/10890923/a4b0bd94-eb81-4cd7-abe3-91e0b29dcbc3)

### Annonsblockerare och version

uBlock Origin 1.58.0

### Webbläsare och version

Firefox 126.0.1

### Konfiguration

<details>
<summary>Detaljer</summary>

```yaml
uBlock Origin: 1.58.0
Firefox: 126
filterset (summary):
 network: 142002
 cosmetic: 124556
 scriptlet: 28812
 html: 2111
listset (total-discarded, last-updated):
 removed:
  plowe-0: null
 added:
  easylist-annoyances: 4644-49, 6d.23h.5m
  easylist-chat: 196-0, 4d.23h.17m
  fanboy-cookiemonster: 51100-184, 18m
  easylist-newsletters: 7474-20, 6d.23h.5m
  easylist-notifications: 3017-164, 6d.23h.5m
  fanboy-social: 16102-16, 6d.23h.5m
  ublock-annoyances: 5859-81, 1h.36m Δ
  SWE-1: 4621-49, 1h.36m Δ
  ublock-cookies-easylist: 1166-3, 6d.23h.5m
 default:
  user-filters: 3-0, never
  ublock-filters: 38390-112, 1h.36m Δ
  ublock-badware: 9102-1, 1h.36m Δ
  ublock-privacy: 921-2, 1h.36m Δ
  ublock-unbreak: 2384-2, 1h.36m Δ
  ublock-quick-fixes: 88-3, 1h.36m Δ
  easylist: 86497-170, 1h.36m Δ
  easyprivacy: 51012-65, 1h.36m Δ
  urlhaus-1: 15910-0, 18m
filterset (user): [array of 3 redacted]
trustedset:
 added: [array of 7 redacted]
userSettings:
 contextMenuEnabled: false
 prefetchingDisabled: false
 showIconBadge: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 184 ms (selfie)
 maxAssetCacheWait: 73 ms
 cacheBackend: indexedDB
```
</details>

**Comment by lassekongo83** [comment]
Rapportera till easylist. https://github.com/easylist/easylist#fanboy-lists
