### ISSUE TITLE
overzealous wrt prisjakt?

### ISSUE THREAD

**Issue by abjorck** [lassekongo83/Frellwits-filter-lists#2]
Hej
Blocking all of prisjakt and/or pji.nu (that they use as cdn) is making that whole site unusable. I find it quite usable without these two rules. Are there ads hosted from these domains on other sites? (I haven't noticed any, maybe some other rule takes care of them) 
Or are you of the opinion that all of prisjakt is an ad? Not judging, just wondering ;)

**Comment by lassekongo83** [comment]
Prisjakt as a third party on other websites can be considered to be advertisements. 1st party rule however needed to be fixed.

**Comment by birgander** [comment]
Hi,

It still blocks CSS, JS and images for international versions of Prisjakt, like https://www.prisjakt.no and https://pricespy.co.uk. They all use the same CDN.
