### ISSUE TITLE
Problem med videolänkar på di

### ISSUE THREAD

**Issue by erssn** [lassekongo83/Frellwits-filter-lists#22]
Tjena, och stort tack för att du delar med dig av det här!

Jag har lite problem med vissa sidor som ska visa video på di.se, ex följande länk:
`https://www.di.se/ditv/nyheter/trump-kan-inte-atalas/`

Någon idé?

Jag kör uBlock i Firefox Quantum, 59.0.3

/Lucas
![untitled3](https://user-images.githubusercontent.com/39119111/40163999-a53d1e08-59b8-11e8-9bdf-b94653a45077.jpg)

**Comment by lassekongo83** [comment]
Klippet fungerar för mig. Vilka andra filter listor har du aktiverat?
