### ISSUE TITLE
abus.com

### ISSUE THREAD

**Issue by davidhedlund** [lassekongo83/Frellwits-filter-lists#29]
### Länk till sidan

abus.com

### Beskriv problemet

Godkännande av kakor visas ej.

### Skärmdump(ar)

Med SWE: Frellwit's Swedish Filter blockerat
![screenshot at 2018-08-27 17 28 39](https://user-images.githubusercontent.com/6416073/44669877-7813b400-aa21-11e8-8695-54d4a9e56062.png)

Med SWE: Frellwit's Swedish Filter aktivt
![screenshot at 2018-08-27 17 29 16](https://user-images.githubusercontent.com/6416073/44669878-7813b400-aa21-11e8-9e6f-8d43345ac0f0.png)

### Versioner

- Browser/version: 1.16.20
- uBlock Origin version: 60.0.1 GNU/Linux (64-bit)

### Inställningar

Default + Swe

**Comment by davidhedlund** [comment]
Tack men det fungerar inte, cookie HTML elementet tas bort efter en millisekund.

**Comment by davidhedlund** [comment]
Man måste se meddelandet för att kunna godkänna kakor. Annars förblir sidan grå.

**Comment by lassekongo83** [comment]
Rensade du cachen när du uppdaterade listan? "Rensa all cache" och "uppdatera nu". Ladda sedan om sidan med CTRL+F5.

**Comment by davidhedlund** [comment]
Ursäkta, jag glömde uppdatera filter listan. Lösningen funkar precis som jag önskade.

Tack så jättemycket, snyggt kodat som vanligt.

**Comment by davidhedlund** [comment]
Men varför gömma godkännande av kakor på abus.com? Det är ju inte en svensk sida.

**Comment by lassekongo83** [comment]
Den verkar ha en svensk översättning för min del i alla fall.

**Comment by davidhedlund** [comment]
Ja det stämmer. Men godkännande av kakor gömms väl inte normalt av uBO filter, snarare av **Annoyances** filterkaterorin, eller?

**Comment by lassekongo83** [comment]
Det står under Description: *A filter for uBlock Origin that aims to remove regional Swedish ads, tracking, **annoyances**, scams + badware, and unnecessary bloat.*

Mer info om vad jag klassar som annoyances: https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Swedish/EXTRA_INFO.md#vad-listan-har-som-mål-att-ta-bort

**Comment by davidhedlund** [comment]
Du har en poäng, hur som helst så är godkännanden av större vikt nu när ny dataskyddsförordningen gått igenom. Nu kan ju inte personer som besöker abus.com godkänna att kakor används. Hur ser du på detta?

**Comment by lassekongo83** [comment]
Eftersom filtret redan har som mål att blockera spårning så ser jag meddelanden om kakor eller GDPR som irrelevanta. Man har redan gjort en opt-out genom att använda annonsblockerare och/eller mitt filter. Om nu inte sidan specifikt kräver att man trycker på "Godkänn" till exempel. (IDG.se är ett exempel om man vill ta del av inbäddade tredjepart videos från YouTube och liknande.) Men sånt är case-to-case.

**Comment by davidhedlund** [comment]
Ok, jag accepterar dina mål.
