### ISSUE TITLE
Hej!

### ISSUE THREAD

**Issue by Bokis** [lassekongo83/Frellwits-filter-lists#30]
Projekten syns inte när uBlock är påslaget, med Frellwit's Swedish Filter.
https://childhood.se/vad-vi-gor/projekt/

Här syns de dock: https://childhood.org/this-is-childhood/projects/

Jag kan inte se vad det är för fel på den svenska sajten.

**Comment by lassekongo83** [comment]
Uppdatera listan listan genom att gå in i inställningar > Tredjepartsfilter. Tryck på `Rensa all cache` och `Uppdatera nu`. Sen ska det fungera.
