### ISSUE TITLE
Regarding potential mirroring of your list and others' lists

### ISSUE THREAD

**Issue by DandelionSprout** [lassekongo83/Frellwits-filter-lists#35]
I'm writing this particular issue in English, since I expect for this to be used as reference material for an issue report in another repo.

In light of recent situations wherein GitHub took offence with the gists of CHEF-KOCH (The maker of a large number of filterlists, most of them anti-corporate), and with NanoMeow (jspenguin2017's issue sorting bot); as well as how many filterlists may be difficult to access in censorship-eager countries (e.g. Iran, possibly PR-China); it's being discussed in https://github.com/NanoAdblocker/NanoCore/issues/220 the importance of keeping backups and mirrors for adblock assets in general.

In that thread, I've proposed unilateral mirror keeping, and I've used your Swedish list as one of the examples of a list that currently has no known mirrors, and which therefore would be in severe trouble if GitHub one day were to disapprove of your list. As you're easily-enough reachable online and technically skilled, I'll ask you the following questions to you, as a gauging of how other list maintainers in similar situations could've reacted:

* Are you okay with the notion that mirrors would be kept for your list(s)?
* Do you feel that it's morally necessary to ask maintainers for permission to host mirrors, or could that be skipped for a greater cause?

**Comment by lassekongo83** [comment]
I have it privately mirrored elsewhere that I can make public if anything happens. I try not to use full domains that can be flagged by GitHub's bots when it comes to piracy, malware and nsfw.

No need to ask for permissions when it comes to hosting mirrors. People are free to make mirrors, forks, etc of this repository. The only thing I can think of is that people setting up mirrors would need to remember `!#include` filters that needs the same source.

**Comment by DandelionSprout** [comment]
I have by now made a mirror at https://repo.or.cz/Adblock-list-backups-Frellwits-filter-lists.git/tree/refs/heads/master, with the partial intention of having it be included in https://github.com/uBlockOrigin/uBlock-issues/issues/278 as a secondary link for your list. However, gorhill seems to have been taking it easy in the past week, so I guess it could still take a while before my issue and [sort-of-pull-request](https://github.com/gorhill/uBlock/compare/master...DandelionSprout:patch-3) is accepted.

**Comment by DandelionSprout** [comment]
This doesn't seem to be a super-relevant issue anymore, for several reasons, so I think this issue can be laid to rest now, as it currently stands.
