### ISSUE TITLE
"Cookiebot" rule creates some issues (Frellwit's Swedish Filter)

### ISSUE THREAD

**Issue by THEtomaso** [lassekongo83/Frellwits-filter-lists#37]
### Issue:
Some third party elements are blocked.

### Example:
`https://www.refinery29.com/en-gb/2018/10/214421/emma-watson-trans-rights/`
(Instagram images are blocked)

### Problem filter:
Frellwit's Swedish Filter

### Problem rule:
`||consent.cookiebot.com^$third-party`

### Thoughts:
Desired behaviour, or not?
The rule might rather belong in a dedicated "privacy" filter perhaps?

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v28.1.0 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.5 (XUL)

**Comment by lassekongo83** [comment]
Made it site specific instead. I still consider it to be a huge annoyance.
