### ISSUE TITLE
Angående den nye gambling-listen din

### ISSUE THREAD

**Issue by DandelionSprout** [lassekongo83/Frellwits-filter-lists#38]
Jeg bidrar ganske mye til FilterLists.com, og vet derfor at det allerede finnes en ganske stor gambling-«hosts»-fil ved navn [Gambling Hosts](https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/gambling-hosts), som har 1 660 oppføringer i skrivende stund, og som er en del av [Unified Hosts](https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews-gambling-porn-social/readme.md)-systemet til [Steven Black](https://github.com/StevenBlack).

Selv om listen din hadde oppføringer som var ganske unike sammenlignet med *Gambling Hosts*, tenkte jeg derfor at jeg like gjerne kunne prøve å slå sammen listene deres med https://github.com/Sinfonietta/hostfiles/pull/35, hvis du ikke har noe imot det.

**Comment by lassekongo83** [comment]
Det låter helt ok.
