### ISSUE TITLE
Videospelare på Expressen

### ISSUE THREAD

**Issue by H2SO4JB** [lassekongo83/Frellwits-filter-lists#4]
Hej Mattias,

Tack för ditt jobb med din filterlista. Den funkar grymt bra!
Jag har dock upptäckt ett litet störande problem. Det är något filter i din lista som ställer till det med Expressens videospelare.
Det är lite svårt att förklara, men om jag tar tag i snabbspolningsreglaget i en video så fastnar reglaget i muspekarens position och släpper inte taget. Och videon spolas varken framåt eller bakåt.

Är det bara jag som upplever detta, eller har du samma problem? I så fall, går det att lösa?
Jag kan spela in en videoscreenshot om så önskas. Jag använder Chrome och uBlock Origin.

Tack på förhand.

**Comment by lassekongo83** [comment]
Forcera en uppdatering av listan. Hojta till om du ser reklam i någon video. Förhoppningsvis behövdes inte det filtret jag använde.
