### ISSUE TITLE
A question regarding e-mail marketing services

### ISSUE THREAD

**Issue by THEtomaso** [lassekongo83/Frellwits-filter-lists#42]
Is it a particularly good idea to block those type of services?

MailChimp, for instance, is used as a third-party service by `campaign-archive.com`, which sends out newsletters for various companies.
Now, if people wish to view these newsletters, or even unsubscribe from them, they will be prevented to do so by the following rule, found in '**Frellwit's Swedish Filter**':
`||mailchimp.com^$third-party`

**Comment by lassekongo83** [comment]
Mailchimp is still advertising in one way or another. They use annoying "popups" that covers the content. Like for example on `mkse.com`. Anything that does that for marketing purposes I consider to be an annoyance or ad. Maybe I could modify that rule to something like `||mailchimp.com^*/popup/$script`. I'll have to do some more testing.
