### ISSUE TITLE
Quora & Twitter

### ISSUE THREAD

**Issue by indolering** [lassekongo83/Frellwits-filter-lists#45]
Please, please get rid of Quora's and Twitter's stupid app spam.  Please!

**Comment by DandelionSprout** [comment]
Have you tried with *uBlock Filters - Annoyances* or *[Browse Websites Without Logging In](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt)*? While their entries for Quora and Twitter primarily concerns login banners, I think there could be some overlap between their login banners and app banners, especially regarding Quora.

Full disclosure: I'm the maintainer of *Browse Websites Without Logging In*, as well as the one who submitted the possibly relevant entries for Quora and Twitter to uAssets.

**Comment by burestad** [comment]
Problems with Viafree, says I have an adblock installed.

**Comment by DandelionSprout** [comment]
Should be pretty recently fixed in Frellwit's list (for Swedish users) and my list (for Norwegian and Danish users). If the issue still prevails after syncing with the lists' newest versions, I presume that a new issue report about the matter should be created.

**Comment by burestad** [comment]
> Should be pretty recently fixed in Frellwit's list (for Swedish users) and my list (for Norwegian and Danish users). If the issue still prevails after syncing with newest version of Frellwit's list, I presume that a new issue report about the matter should be created.

Attempted to sync with the recent update and also enabled yours to no avail. It seems like ViaFree has detected it already.

**Comment by DandelionSprout** [comment]
I can confirm that they're detecting it as well. I'll let Frellwit decide if this is either A) a matter for a separate issue report thread, or B) grounds for re-opening that uAssets and/or [NanoMeow](https://github.com/NanoMeow/QuickReports/issues/456) project threads about `Viafree`. The only thing I can confirm almost for sure, is that this very thread wasn't really meant to be about `Viafree`.

**Comment by lassekongo83** [comment]
Create a new issue if there still are issues about that. But just update your filters for now. Just made a small fix, but it's not a good one. You'll have to wait a while during midrolls. (Seems like nothing is happening, but it will continue eventually.)
