### ISSUE TITLE
nwt.se

### ISSUE THREAD

**Issue by psonnosp** [lassekongo83/Frellwits-filter-lists#5]
Hej!

Vet inte om det här är rätt ställe och be om hjälp gör en chansning.

Aktiverar jag den här listan, som för övrigt funkar jättebra, så ballar inloggningen på nwt.se ur. Uppe i vänstra hörnet där det  vanligvis dyker upp en inloggningsknapp eller ens namn när man loggat in så blir det istället som på bilden nedan, 'Laddar...' står bara och snurrar i all oändlighet.
![capture_3](https://user-images.githubusercontent.com/28609335/31355032-f608b1c6-ad38-11e7-81a2-bfe9df72ffbe.jpg)
Går man in på valfri plusartikel så finns det en bit ner en inloggningsknapp...
![capture_4](https://user-images.githubusercontent.com/28609335/31355596-4691ef0c-ad3b-11e7-961d-7f05d2bf8b60.jpg)
...men klickar man på den händer ingenting när listan är aktiverad.

Går det här och fixa utan att det förstör listan i övrigt?

Mvh pson

**Comment by lassekongo83** [comment]
Forcera en uppdatering av listan. Domänen cxense som finns i listan EasyPrivacy var svartlistad. Nwt verkar behöva något script därifrån för att det ska ladda klart.

**Comment by psonnosp** [comment]
Tack å bock, funkar perfekt :)

**Comment by psonnosp** [comment]
Nu var det dags igen, något i det här filtret blockar inloggningen.
Inloggningen längst uppe i högra hörnet syns inte alls och Logga in-knappen längre ner på sidan reagerar inte på klick. Har försökt lite själv men mina kunskaper räcker inte riktigt till för och lösa det :(

**Comment by lassekongo83** [comment]
Fixat.

**Comment by psonnosp** [comment]
Tackar :)
