### ISSUE TITLE
ViaFree blockas inte längre

### ISSUE THREAD

**Issue by burestad** [lassekongo83/Frellwits-filter-lists#52]
### Länk till sidan

`https://www.viafree.se`

NSFW `https://www.viafree.se/program/reality/paradise-hotel/sasong-10/avsnitt-19`

### Beskriv problemet

Får upp att jag har en ad-blocker aktiverad under varje reklampaus. Det går att komma förbi problemet om man spammar CTRL + F5 cirka 3-4 gånger. 

### Skärmdump(ar)

[När problemet är svårt att beskriva i text.]

### Versioner

- Webbläsare/version: Google Chrome Version 73.0.3683.103 (64 bitar)
- uBlock Origin version: 1.18.16

### Inställningar

- N/A

**Comment by lassekongo83** [comment]
Kan du prova?
```
||client-stream-events.mtg-api.com^$xhr
viafree.se##+js(addEventListener-defuser.js, error)
viafree.se##+js(addEventListener-defuser.js, abort)
viafree.se##+js(addEventListener-defuser.js, load, (t,n))
```

Det kommer dock att vara en lång väntetid vid midroll.

**Comment by burestad** [comment]
> Kan du prova?
> 
> ```
> ||client-stream-events.mtg-api.com^$xhr
> viafree.se##+js(addEventListener-defuser.js, error)
> viafree.se##+js(addEventListener-defuser.js, abort)
> viafree.se##+js(addEventListener-defuser.js, load, (t,n))
> ```
> Det kommer dock att vara en lång väntetid vid midroll.

Tack. Det fungerar.

**Comment by burestad** [comment]
> Kan du prova?
> 
> ```
> ||client-stream-events.mtg-api.com^$xhr
> viafree.se##+js(addEventListener-defuser.js, error)
> viafree.se##+js(addEventListener-defuser.js, abort)
> viafree.se##+js(addEventListener-defuser.js, load, (t,n))
> ```
> Det kommer dock att vara en lång väntetid vid midroll.

Nu kommer ad-block varningen upp igen. Skedde efter tredje reklampausen på `https://www.viafree.se/program/reality/paradise-hotel/sasong-10/avsnitt-22` NSFW.

**Comment by lassekongo83** [comment]
Har ingen lösning just nu.

**Comment by burestad** [comment]
Nu verkar ad-blocker varningen poppa upp direkt efter första reklampausen och går inte att få bort trots CTRL + F5

**Comment by mlonn** [comment]
Länken fungerar för mig nu utan att lägga till de föreslagna reglerna. Adblockvarningen flimrar förbi och klippet pausas men går att starta igen direkt.
