### ISSUE TITLE
https://www.ilikeradio.se

### ISSUE THREAD

**Issue by seba2282** [lassekongo83/Frellwits-filter-lists#53]
### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues.]

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

- [List here all the changes you made to uBO's default settings]

Adguard Android with much filters
Browser Firefox 

`https://www.ilikeradio.se`
After yesterday updating Swedish filter in browser I don't see cookies again but that update destroyed players radios. When I try click play, any player doesn't start play. Can you fix that? 
Best Regards

**Comment by lassekongo83** [comment]
Can't reproduce. Works fine with default setup in uBlock Origin Firefox Android extension. Note that I don't officially support Adguard. But in this case you may have another filter that's causing an issue. Try with a default setup without any other 3rd party filters activated.

**Comment by seba2282** [comment]
Problem is in that filter. When I turn off that filter, I see ads, cookies and players works. But when turn on then only players can't play. I tested with turn off single filters. After finding problematic, I reported you. It is after yesterday evening update.

**Comment by lassekongo83** [comment]
What happens if you add. `ilikeradio.se#@#.cc-window.cc-floating` and accept the cookie message?

**Comment by seba2282** [comment]
After added your rule to user filters, I haven't still cookies, what is good information. And still players doesn't work.

**Comment by lassekongo83** [comment]
Then the issue must be at your end, or with Adguard (which I don't support). Try disabling Adguard and use uBlock Origin instead. I've not added any new filters that should affect the player on that website.

**Comment by seba2282** [comment]
Can you tell which filters you have? Mean names. Always your filters worked great with adguard. Only was one update and that stopped work.

**Comment by lassekongo83** [comment]
```
uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak​​​​​

EasyList​​​​​

EasyPrivacy

Malware Domain List
Malware domains

Peter Lowe’s Ad and tracking server list

SWE: Frellwit's Swedish Filter
```

**Comment by seba2282** [comment]
I try now turn only that what can in Adguard (ublock aren't here). And give you informations after testing. After try w Ublock Origin. I know only UBO doesn't block to much and block not aggressive. Adguard has specific rules/scripts. I love him by that. He skip anti adblock very good with his scripts. How I said earlier, problem start with Swedish radios on that site, when activate Swedish filters.

**Comment by seba2282** [comment]
I turned all options with privacy (hidden mode), dns filtering, turned Adguard filters. I have only Polish (my region) and filters like you. And if turn off filter Swedish then start work with ads and cookies and players. Suggest? I try now with Ublock Origin.

**Comment by seba2282** [comment]
I see works now. Maybe seriously filter isn't compatible with Adguard / Nano Adblocker. Temporary close topic. I will write later if will know more what block in Adguard.

**Comment by seba2282** [comment]
In Adguard some filter blocks app.khz.se 
I added rule: 
@@||app.khz.se 
And all start work.
