### ISSUE TITLE
svd.se bilder blockeras

### ISSUE THREAD

**Issue by Vms7** [lassekongo83/Frellwits-filter-lists#57]
### Länk till sidan

svd.se

### Beskriv problemet

Många bilder på Svenska Dagbladet blockeras efter senaste uppdateringen.  Bilderna syns om man avaktiverar filtret. Är prenumerant och inloggad på svd.se

### Skärmdump(ar)

![image](https://user-images.githubusercontent.com/53994052/62832517-0af82f00-bc30-11e9-9299-e0b49f36ff8e.png)

### Versioner

- Webbläsare/version: Firefox 68.0.1, Windows 10 1903
- uBlock Origin version: uBlock Origin v1.21.2

### Inställningar

Inga speciella

**Comment by lassekongo83** [comment]
Det ska vara fixat nu.  [Uppdatera listan manuellt](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now).

**Comment by Vms7** [comment]
Tackar! Funkar perfa.
