### ISSUE TITLE
Unable to access aftonbladet.se 

### ISSUE THREAD

**Issue by DrZingo** [lassekongo83/Frellwits-filter-lists#61]
### URL(s) where the issue occurs
`https://www.aftonbladet.se/`

### Describe the issue
aftonbladet.se is not accessible when the following rule is active:
`/privacy/notification?$xmlhttprequest,domain=aftonbladet.se`

When commenting it out, aftonbladet works.
`! /privacy/notification?$xmlhttprequest,domain=aftonbladet.se`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/6590732/66146414-05560e80-e60d-11e9-9d3a-fe9a1b24e5bf.png)

### Versions

- Browser/version: brave
- uBlock Origin version: brave built-in blocking with `SWE: Frellwit's Filter List` enabled

### Settings

- All blocking rules as default + enabled `SWE: Frellwit's Filter List`

**Comment by lassekongo83** [comment]
Can you reproduce the issue in any other browser than Brave with uBlock Origin installed?

Unable to reproduce in Firefox or Chromium.
