### ISSUE TITLE
Blockerad video på Expressen

### ISSUE THREAD

**Issue by H2SO4JB** [lassekongo83/Frellwits-filter-lists#63]
Hej Mattias,

Jag upptäckte idag att något i ditt filter blockerar den översta stora videon på Expressen.
Bifogade bilder talar för sig själv. Kan du undersöka detta? Tack på förhand...

![2019-10-16_120328](https://user-images.githubusercontent.com/13471707/66909753-9a91d380-f00d-11e9-97a0-a0445af95326.jpg)
![2019-10-16_120337](https://user-images.githubusercontent.com/13471707/66909756-9c5b9700-f00d-11e9-9b78-42ca942f5018.jpg)

**Comment by lassekongo83** [comment]
Det är meningen att live-spelaren på förstasidan ska blockeras då den är irriterande med autostart. Klickar man på länken så ska man kunna se videon. Jag kan däremot ta bort utrymmet den lämnar efter sig.

**Comment by H2SO4JB** [comment]
Jaha, jag förstår. Nu ser det bättre ut när jag uppdaterade ditt filter. Tack!

Något som är ännu mer irriterande är den blåa bannern ovanför som hela tiden tjatar om att man ska betala för Premium. Jag har blockerat den med eget filter, men de byter budskap i den med jämna mellanrum, så jag måste omblockera den ofta. Det hade varit bra om du kunde blockera den DIVen helt och hållet. Jag har inte tillräcklig kunskap för det.  :-)
![2019-10-16_124441](https://user-images.githubusercontent.com/13471707/66912449-e2672980-f012-11e9-88a0-77694d8668c3.jpg)

**Comment by lassekongo83** [comment]
Prova med `expressen.se##.livetv-widget + .linked-image-widget`

Detta filtret tar dock inte bort självpromotion av sidors egna premium-tjänster och liknande, så vidare de inte 1. Täcker över innehåll eller avbryter besökaren. 2. Tar tid att ladda. 3. Är någon form av scam.

*(Sen om man inte är intresserad av deras premium-tjänst så kan man även lägga till ett personligt filter som plockar bort alla premium-artiklar på sidan. `expressen.se##.premium-link`)*

**Comment by H2SO4JB** [comment]
Vad grym du är! Tack som fan!  :-)

**Comment by H2SO4JB** [comment]
Åter igen, tack för tipset av följande lösning: `expressen.se##.premium-link`
 Det funkar skitbra! Finns det en lika enkel lösning för att blockera alla Aftonbladets Plus-tjänster som du kan dela med dig tro?  :-)

**Comment by lassekongo83** [comment]
`aftonbladet.se##a:has([href="#plus-logo"])`

**Comment by H2SO4JB** [comment]
Vad grym du är! Tack som fan!  :-)

**Comment by H2SO4JB** [comment]
Hej Mattias,

Jag hittade det här gamla ärendet där du för ca två år sedan hjälpte mig med en regel som utplånar alla Premium/Plus-artiklar på både Expressen och Aftonbladet. Båda har fungerat perfekt tills nyligen då jag nu upplever att Aftonbladets Plus-artiklar visas igen. De har förmodligen ändrat något och jag har inte kunskap att ta reda på vad. Detta har ju inte med ditt filter att göra men har du tid/lust att hjälpa mig att ta reda på hur den nya regeln ska se ut? I så fall är jag jättetacksam! 👍🏻

**Comment by lassekongo83** [comment]
Prova: `aftonbladet.se##title:has-text(abplus):upward(a)`

**Comment by H2SO4JB** [comment]
Fan, vad grymt du är! Tack så mycket!
Kan man donera till dig på något sätt för ditt arbete?
