### ISSUE TITLE
I Don't Want Your App , LinkedIn

### ISSUE THREAD

**Issue by s-ankur** [lassekongo83/Frellwits-filter-lists#64]
Please block the "Linkedin works better if you switch to our app UwU" message on

`https://www.linkedin.com/`

### Screenshot(s)
User Agent:
![image](https://user-images.githubusercontent.com/33252312/68390561-8fa10d80-018b-11ea-930a-c2dbbe5d4773.png)
Website:
![image](https://user-images.githubusercontent.com/33252312/68390452-55d00700-018b-11ea-91ae-a77581f9975e.png)

### Versions

- Browser/version:70.0.1 (64-bit) Firefox
- uBlock Origin version: uBlock Origin v1.23.0

**Comment by lassekongo83** [comment]
Unable to reproduce.

**Comment by s-ankur** [comment]
Have you logged in? It does not appear if not

**Comment by lassekongo83** [comment]
I don't have an account. Mind right-clicking on the gray area, select inspect element and show me what the DOM looks like?

**Comment by s-ankur** [comment]
![image](https://user-images.githubusercontent.com/33252312/68473734-c50c3080-0249-11ea-893c-80a8b9867616.png)
I can block the whole thing using 
`www.linkedin.com###app-upsell-container`
but then it wont scroll

**Comment by lassekongo83** [comment]
Does the scroll work if you add? `linkedin.com##html,body:style(overflow: auto !important;)`

**Comment by s-ankur** [comment]
Yes, it works
