### ISSUE TITLE
Nyafilmer

### ISSUE THREAD

**Issue by nyafilmerhd** [lassekongo83/Frellwits-filter-lists#70]
### URL(s) where the issue occurs

https://nyafilmer.lol
https://nyafilmer.lol/login

### Describe the issue

||nyafilmer.*$csp=default-src 'self' 'unsafe-inline' 'unsafe-eval' jawcloud.co *.jawcloud.co *.googleapis.com *.google.com *.gstatic.com;img-src *;worker-src 'none'

This rule is blocking our analytics scripts. It's okay you are blocking ads, share buttons and twitter but analytics is mandatory for us to know about our visitors. We kindly ask you to remove this rule and prevent ads with a different way or modify it to make analytics scripts work again.

Here's our analytics scripts;
https://www.googletagmanager.com/gtag/js?id=UA-123052772-1
https://s10.histats.com/js15_as.js

Regards.

**Comment by lassekongo83** [comment]
Blocked in EasyPrivacy/Peter Lowe's list anyways. Also the idea is to block analytics as well. Declined.
