### ISSUE TITLE
Flera cookies på http://bokat.se/protected/groupInfo.jsp saknas

### ISSUE THREAD

**Issue by Inspireless** [lassekongo83/Frellwits-filter-lists#72]
Hej,

Besöker jag bokat.se hemma, blockerar Pi-hole en del av sidans funktioner, men av en slump besökte jag sidan via min mobiltelefon med Adblock Browser. Då fick jag upp en ruta att godkänna cookies. När jag tryckte på Visa säljare, listade den flera hundra länkar.

Prova om "disclamer" kommer upp om du besöker: http://bokat.se/protected/groupInfo.jsp 

Annars är det gömt under Integritet. 

Jag har inte kunskaperna att spara förteckningen. Det kanske du har. Har redan skrivit om det här till en annan administratör utan respons. Se: https://github.com/deathbybandaid/piholeparser/issues/104

Månne är en svensk mer intresserad så sidan är populär är. Dock kan sidan göra en adblock-lista mer komplett.

Tack på förhand.

**Comment by lassekongo83** [comment]
Jag förstår inte riktigt. Menar du att alla domäner under "Visa säljare" ska läggas till i hosts-filen? Eller är det något specifikt som inte fungerar?

**Comment by Inspireless** [comment]
Korrekt uppfattat. Förteckningen över alla cookies man godkänner, kan komplettera blocklistorna. 

Min Pi-hole filtrerar bort länken. Stänger jag av wifi på mobiltelefonen, kommer rutan upp som visar alla cookies man godkänner eller nekar. Visar med screenshots hur det ser ut.

**Comment by lassekongo83** [comment]
Det räcker med att blockera de ordinarie anslutningarna från sidans källkod. Resten ansluts inte om man inte har vitlistat någon av sidans annons/spårningsdomän.
