### ISSUE TITLE
Fel vid PiHole import

### ISSUE THREAD

**Issue by eplusg** [lassekongo83/Frellwits-filter-lists#75]
### Länk till sidan

**N/A**

### Beskriv problemet
Filter listan ger ett fel när man importerar den i Pi-Hole. Vet inte om det är tänkt att supporteras men vore toppen om det gick att lösa.
Hosts-filen fungerar bra.

**Felmeddelande:**
 [i] Target: https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Filter.txt
  [✓] Status: Retrieval successful
  [i] Received 1621 domains, 666 domains invalid!
      Sample of invalid domains:
      - 2.0]
      - &log_ad$image,domain=yelp.se
      - &type=load_offers$xmlhttprequest,domain=illvet.se|pctidningen.se
      - 'none',domain=svtt.se|ssvd.se|exressen.se|eexpressen.se|sskatteverket.se|aatg.se|atgg.se
      - -ads.$image,domain=svenskbyggtidning.se

### Skärmdump(ar)
**N/A**

### Versioner
**N/A**

### Inställningar
**N/A**

**Comment by lassekongo83** [comment]
Filter listan fungerar ej i pi-hole. Den är skriven enbart för uBlock Origin/Nano Adblocker.
