### ISSUE TITLE
Cookie/GDPR-meddelande på Blocket

### ISSUE THREAD

**Issue by H2SO4JB** [lassekongo83/Frellwits-filter-lists#76]
Hej Mattias,
Kan/vill du filtrera bort cookie/GDPR-meddelandet på Blocket som täcker hela skärmen?
Det går att komma förbi genom att bara klicka bredvid det, men det hade varit trevligt om det försvann för gott.  :-)
![2020-06-15_110454](https://user-images.githubusercontent.com/13471707/84639773-2475a180-aef9-11ea-9aeb-d1dc63606aeb.jpg)

**Comment by lassekongo83** [comment]
Den kräver att man accepterar för att kunna klicka på länkar på sidan, men det går att komma runt. 

En aningen oprövad metod som kanske slutar fungera eller gör att något annat går sönder på sidan.
Prova:
```
blocket.se##[data-testid="modal-background"]:has([data-testid="info-dataskydd-link"])
blocket.se##+js(aeld, click, b(e))
```

**Comment by H2SO4JB** [comment]
Hej,
Är du säker på det första du säger? Jag har "hängt" på Blocket i en månad nu och jag klickar alltid bort rutan genom att klicka på det gråa fältet utanför rutan. Jag har aldrig märkt att någon länk inte fungerar.

**Comment by lassekongo83** [comment]
När du klickar bort rutan så accepterar du. Om du tar bort rutan från DOM utan någon input från användaren så slutar alla länkar att fungera.

**Comment by H2SO4JB** [comment]
Jaha, fan vad sjukt! Att det ens är tillåtet i enlighet med GDPR?
Jaja, jag testade din andra metod och den funkade perfekt.
Frågan är hur länge, men tack för förklaringen och hjälpen.
