### ISSUE TITLE
Viafree funkade fram till 20200712 så att reklamen bara hoppades över - ej längre. Ej heller manuellt hoppa över.

### ISSUE THREAD

**Issue by aastrid** [lassekongo83/Frellwits-filter-lists#78]
### Länk till sidan (exempel)
`https://www.viafree.se/program/drama/the-oc/sasong-3/avsnitt-1`

### Beskriv problemet
Viafree funkade fram till 20200712 så att reklamen bara hoppades över - ej längre. Ej heller manuellt hoppa över.
[Var så tydlig som möjligt]

- Webbläsare/version: [här]
Firefox x64   | 78.0.2 Win10pro
- uBlock Origin version: [här]
1.28.2
### Inställningar
Inga
- [Lista alla ändringar du gjort till uBlock Origins originalinställningar.]

**Comment by lassekongo83** [comment]
Allt fungerar som det ska för mig. Se till att du inte har några andra annonsblockerare installerade. Kolla även så att allt står rätt till med Firefox: `https://firefox-storage-test.glitch.me/` (Alla 4 ska vara `Good: Totally Working.`)
