### ISSUE TITLE
Jag fant uppföringer för Ålandssvenska websidor

### ISSUE THREAD

**Issue by DandelionSprout** [lassekongo83/Frellwits-filter-lists#79]
### Länk till sidan + Beskriv problemet

Jeg fant oppføringer for Ålandssvenske nettsteder:
```
! https://www.bilwebben.ax/
bilwebben.ax###secondary-content-wrapper:has(.block:only-child)
! https://www.bosidan.ax/
bosidan.ax##.ad-li
! https://www.nyan.ax/
.ax/ad/
```

### Skärmdump(ar)

Ser ikke ut til å være nødvendig. Jeg kan legge til skjermklipp for individuelle nettsteder ved behov.

### Versioner

- Webbläsare/version: Chrome 84.0.4147.105 x64
- uBlock Origin version: Nano Adblocker 1.0.0.152 + Nano Defender 15.0.0.201

### Inställningar

![image](https://user-images.githubusercontent.com/22780683/88781267-76624600-d18c-11ea-9888-d57f96c6d326.png)
![image](https://user-images.githubusercontent.com/22780683/88781301-837f3500-d18c-11ea-95f0-789f65bff9a8.png)

**Comment by lassekongo83** [comment]
Kan inte hitta något på `bilwebben.ax`. Verkar redan vara blockerat i EasyList.

**Comment by DandelionSprout** [comment]
På `bilwebben.ax` dreier det seg om plassholderen oppe på forsiden: 
![image](https://user-images.githubusercontent.com/22780683/88787169-bf69c880-d193-11ea-9918-fa37f9c07530.png)
