### ISSUE TITLE
Det finnes allerede en norsk filterliste

### ISSUE THREAD

**Issue by DandelionSprout** [lassekongo83/Frellwits-filter-lists#8]
Hallo, Lasse (Mattias?). 👋 Siden jeg ikke har noen Reddit- eller DeviantArt-kontoer, og at jeg ikke kjenner til noen PM-funksjon på GitHub, så håper jeg at det er like greit å kontakte deg om dette her.

Jeg la merke til den følgende linjen i Frellwit's Swedish Filter: _! Some Norwegian sites. (If this gets too big I'll probably create a seperate filter.)_. Så jeg tenkte jeg kunne tipse deg om at en sådan filterliste allerede finnes: https://github.com/DandelionSprout/adfilt/blob/master/ExperimentalNorwegianList.txt . Jeg har klart å få den akseptert til [Adblock Plus sitt sekundære arkiv](https://adblockplus.org/subscriptions), men har ennå ikke klart å finne ut av hvordan jeg får gorhill til å merke til den og legge den til i uBlock Origin... 😓

Samtidig er listen min noe jeg kun jobber på med noen ukers mellomrom nå til dags, i tillegg til at du ser ut til å være bedre enn meg til å bruke f.eks. $script-funksjoner; så hvis du ønsker å jobbe med den, låne fra den, få redigeringstillatelser på den, hva som helst egentlig, så bare si ifra om det. Listen min er såklart også åpen-kildet. 😄

**Comment by lassekongo83** [comment]
> men har ennå ikke klart å finne ut av hvordan jeg får gorhill til å merke til den og legge den til i uBlock Origin

Prova med att svara i denna: https://github.com/gorhill/uBlock/issues/886
Eller öppna en ny issue där.

Behöver du hjälp med någon Norsk sida kan du alltid kontakta mig här. Jag besöker inte så många Norska sidor själv för att kunna upptäcka alla annonser, anti-adblock, med mera. Sen börjar min egna lista bli väldigt stor vilket gör att jag måste kontrollera väldigt många sidor där nån gång per vecka. :P

Ett litet tips bara. Jag såg att du la till några specifika uBO filter i din lista. Om du vill att listan fortfarande ska vara kompatibel med Adblock Plus och andra adblockers så kan du använda dig av `!#include`. [Exempel](https://github.com/MajkiIT/polish-ads-filter/issues/4898). 

uBO specifika filter som du kan lägga i en extern lista:

`:has(...), :has-text(...), :if(...), :if-not(...), :matches-css(...), :matches-css-before(...), :matches-css-after(...), :xpath(...), :style(), ##script:inject()`
`important`
`badfilter`
`redirect`
`inline-script`
`exempel.no##^.badstuff`

**Comment by DandelionSprout** [comment]
>Behöver du hjälp med någon Norsk sida kan du alltid kontakta mig här.

Jeg har lært mye om adblock-filtre og -lister siden sist vi møttes, men siden jeg nå sliter med et filter, tenkte jeg at jeg skulle følge opp tilbudet ditt, selv om dette forsåvidt ikke handler om en norsk side.

I forbindelse med at jeg for tiden lager en [anti-IMDB-liste](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Anti-IMDB%20List.txt), siden jeg ikke stoler på IMDB-brukernes smak i tegneserier (De har litt for mange hipstere som blindt forguder voldsballaden Powerpuffjentene og som hater Teen Titans GO), forsøker jeg å lage et filter for Google som ville ha fjernet rangeringsscorene(?) til imdb.com-søkeresultatene (Området som er ringet rundt i oransje i skjermklippet nedenfor).

Alt jeg har lært om adblocklister skulle tilsi at `google.*##div.pb.g:has-text(imdb) > div > .rc > .s > div > .f.slp`, eventuelt for eksempel `google.com,google.no,google.se##div.pb.g:-abp-contains(imdb) > div > .rc > .s > div > .f.slp`, burde ha fungert, men Nano Adblocker (og dermed sannsynligvis også uBO) ser ikke ut til å støtte bruken av `>` etter `:has` eller `:has-text`, merkelig nok. Så da lurer jeg om du kunne ha hjulpet meg med dette, siden jeg også har lagt merke til at du har lyktes i å hjelpe mange folk på Reddit med sine problemer.
![image](https://user-images.githubusercontent.com/22780683/43675148-a21e3256-97df-11e8-8ecc-03fac0035730.png)

**Comment by lassekongo83** [comment]
Enbart [xpath](https://www.w3schools.com/xml/xpath_intro.asp) filter kan ge en sån precision. Detta fungerade för mig:

```
google.*##:xpath(//a[text()[contains(., 'IMDb')]]/parent::h3/parent::div[@class="rc"]/descendant::div[@class="s"]/descendant::div/descendant::div[contains(@class, 'slp') and contains(@class, 'f')])
```

**Comment by DandelionSprout** [comment]
Jeg foretrekker uBO/Nano fremfor ABP uansett, og IMDB-listen min var siktet inn mot uBO/Nano/AdGuard (som jeg vanligvis bruker fellesbetegnelsen "avanserte blokkerere" som en fellesbetegnelse for).

Jeg kunne aldri på en million år ha klart selv å finne ut av og lage et såpass langt og detaljert xpath-filter, så jeg gir deg tusen hjertelige takk for hjelpen! 💛

**Comment by lassekongo83** [comment]
Lite bättre och kortare än det förra:
```
google.*##:xpath(//a[text()[contains(., 'IMDb')]]/parent::h3/parent::div[@class="rc"]/div[@class="s"]/div/div[contains(@class, 'slp') and contains(@class, 'f')])
```

**Comment by DandelionSprout** [comment]
Okei, jeg har tenkt at det ville være dumt om jeg spurte deg om hjelp veldig ofte, men nå er det 2 ting jeg føler jeg trenger hjelp til igjen:

1) Jeg har i det siste jobbet med noen lister for YouTube og Wikia, og da er det ett problem: Logoene deres, som lenker til ganske dårlige og kaotiske hjemmesider (youtube.com og fandom.wikia.com). Det er veldig enkelt å fjerne logoene fullstendig, men det frykter jeg ville ha ført til at folk ble forvirret eller skeptiske når de ikke så nettstedenes offisielle logoer.

Jeg lurer derfor på om det finnes noen måte å fjerne (eller endre) lenker fra stillbilder, og å la bildene bli igjen som vanlige bilder? Eksempler:
![image](https://user-images.githubusercontent.com/22780683/46880199-4a0af780-ce48-11e8-98d6-720992b267a6.png)

Én teoretisk mulighet jeg har sett i Chrome sin utviklerkonsoll, er å blanke ut href-verdien til bildene, sånn at de i stedet lenker til siden som du allerede er på.

2) Denne er ment for personlige formål. Jeg er ikke noen superfan av Reddit, men det hender at jeg blar gjennom noen få subredditer. Problemet med det er at 99% av populære subredditer er fyllt opp av reposter, drama, irrelevante spørsmål, eller umorsomme ting. Jeg lurer derfor på om det finnes en måte å fjerne innlegg som har mindre enn for eksempel 20 eller 15 poeng?

Det er verdt å nevne at jeg ikke er innlogget under disse visittene (Jeg prøvde å lage en Reddit-konto en gang. Jeg slettet den etter 90min.), og at hovedfokuset mitt er på det nye grensesnittet (Grensesnittet til new.reddit.com). Tilfeldige eksempler hentet fra r/europe: 
![image](https://user-images.githubusercontent.com/22780683/46880425-df0df080-ce48-11e8-8717-29ba92e20c2a.png)

**Comment by lassekongo83** [comment]
1. Det här kanske:

        youtube.com###logo:style(pointer-events: none !important; cursor: default !important;)
        wikia.com##.wds-global-navigation__logo:style(pointer-events: none !important; cursor: default !important;)

2. `reddit.com##:xpath(//button[@aria-label="upvote"]/following-sibling::div[number() <= number(15)]/ancestor::div[contains(concat(' ', @class, ' '), ' Post ')])`

Jag börjar med att söka igenom efter upvote-knappen, sen letar jag efter div:en som ligger nedanför den och kollar om den har ett värde mindre eller lika med 15 `<=`. (Byt ut till `<` om du vill visa inlägg med 15 poäng också.) Till sist så går jag upp ett antal steg i DOM till klassen `.Post` som kommer att döljas av filtret.

**Comment by DandelionSprout** [comment]
Det er en grunn til at jeg ser opp til deg som den beste filterskriveren i verden. Særlig når alle tre av de filterforslagene virket! 💙💛

Jeg skal memorere den bruken av *pointer-events* og *cursor*, sånn at jeg kan skrive slike bildefiltre selv i fremtiden. Men jeg må innrømme at Xpath sin syntaks ser helt gresk ut for meg, siden jeg ikke er særlig god med datakodespråk, så jeg ville fått litt problemer med å lære å skrive Xpath-filtre på egenhånd.
