### ISSUE TITLE
Filmtipset.se sidebar

### ISSUE THREAD

**Issue by psonnosp** [lassekongo83/Frellwits-filter-lists#82]
`Länk: https://www.filmtipset.se/`

### Beskriv problemet

Listan till höger med länkar till olika genres plockas bort av filmtipset.se###topslider-wrapper + .container > .sidebar (tror jag)
Kanske är nån relik från den gamla sidan?

### Versioner

- Webbläsare/version: Waterfox Classic 2020.07.2 (64-bit)
- uBlock Origin version: 1.29.0

**Comment by lassekongo83** [comment]
Det är bara på första-sidan jag plockat bort sidebaren vad jag vet. Och det med all rätt på grund av alla casino-annonser som har text utanför html-taggar. Genre-listan går att komma åt från andra sidor vad jag kan se.

**Comment by psonnosp** [comment]
I Waterfox så visas ingen reklam där utan bara till höger om genre-listan. Men kollade nu hur det såg ut i Chrome så då förstår jag varför regeln finns och varför den ska va kvar.
![Untitled-1](https://user-images.githubusercontent.com/28609335/90696247-34ed2400-e27c-11ea-9ece-5d9d55a6c2b1.png)
