### ISSUE TITLE
Independent.co.uk - Embedded videos blocked (Frellwit's Swedish Filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [lassekongo83/Frellwits-filter-lists#86]
### Affected site:
`https://www.independent.co.uk/`

### Issue:
Embedded videos are missing, because of a blocked cookie consent, which needs to be accepted!

### Example:
`https://www.independent.co.uk/arts-entertainment/films/news/godfather-iii-edit-francis-ford-coppola-mario-puzo-al-pacino-a9704361.html`

### Problem filter:
* Frellwit's Swedish Filter

### Problem rule:
`||consensu.org^$third-party,domain=~crfashionbook.com|~joe.ie|~mirror.co.uk|~sourceforge.net|~sportsjoe.ie|~vi.nl`

### Screenshot:
Not needed, as the problem is obvious.

### Blocked assets:
```
https://quantcast.mgr.consensu.org/choice/jAJ_WUYAnDzxn/www.independent.co.uk/choice.js
https://quantcast.mgr.consensu.org/GVL-v2/vendor-list.json
https://quantcast.mgr.consensu.org/tcfv2/12/cmp2ui.js
https://quantcast.mgr.consensu.org/tcfv2/cmp2.js
```

### Possible fix:
```
- ||consensu.org^$third-party,domain=~crfashionbook.com|~joe.ie|~mirror.co.uk|~sourceforge.net|~sportsjoe.ie|~vi.nl

+ ||consensu.org^$third-party,domain=~crfashionbook.com|~independent.co.uk|~joe.ie|~mirror.co.uk|~sourceforge.net|~sportsjoe.ie|~vi.nl
```

### Temporary fix:
```
@@||quantcast.mgr.consensu.org/*/choice.js$domain=independent.co.uk
@@||quantcast.mgr.consensu.org/*/cmp2*.js$domain=independent.co.uk
@@||quantcast.mgr.consensu.org/*/vendor-list.json$domain=independent.co.uk

```
### Other problem filters:
* **AdGuard Annoyances filter** https://github.com/AdguardTeam/AdguardFilters/issues/63403/
`||consensu.org^$third-party`
`||quantcast.mgr.consensu.org^$third-party`

* **EasyList Cookie List** / **Fanboy's Annoyance List** https://github.com/ryanbr/fanboy-adblock/issues/1407/
`||quantcast.mgr.consensu.org/choice/$script`
`||quantcast.mgr.consensu.org^*/choice.js$third-party`

* **I don't care about cookies** _(NOTIFIED)_
`quantcast.mgr.consensu.org$domain=~sourceforge.net|~vi.nl|~joe.ie|~cnews.fr`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.13.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.25 (XUL)

**Comment by bug-rules** [comment]
`~cnews.fr`
`~joe.co.uk`
`~today.it`
`~tumblr.com`

```
||quantcast.mgr.consensu.org^$domain=~cnews.fr|~crfashionbook.com|~independent.co.uk|~joe.co.uk|~joe.ie|~mirror.co.uk|~sourceforge.net|~sportsjoe.ie|~today.it|~tumblr.com|~vi.nl
```
