### ISSUE TITLE
AdGuard støtter nå oversettelser av liste-navn og -beskrivelser. Har du noen ønsker om det for listen din?

### ISSUE THREAD

**Issue by DandelionSprout** [lassekongo83/Frellwits-filter-lists#95]
### Länk till sidan

`Länk: https://crowdin.com/project/adguard-applications`

### Beskriv problemet

AdGuard har i noen år tillatt oversettere å oversette titlene og beskrivelsene til AdGuards egne lister, men nå har de tydeligvis også tillatt det for tredjepartslister, inkludert Frellwit's Swedish Filter.

De to strengene man kan oversette, er `Frellwit's Swedish Filter` og `A filter for uBlock Origin that aims to remove regional Swedish ads, tracking, social media, annoyances, sponsored articles etc.`

Har du noen spesifikke ønsker om hvordan disse skal oversettes til svensk og/eller noen andre språk? I tillegg, vil du at tittelen (Frellwit's Swedish Filters) i det hele tatt skal oversettes til noen språk, eller at jeg skal be AdGuard om å bestemme at tittelen ikke skal oversettes?

### Skärmdump(ar)

![image](https://user-images.githubusercontent.com/22780683/99016371-467e5900-2557-11eb-91a6-8c852988545b.png)

### Versioner

- Webbläsare/version: Chrome 86.0.4240.193 x64
- uBlock Origin version: 1.30.9b16 + AdGuard for Windows 7.5.2 + I Don't Care About Cookies 3.2.4

### Inställningar

N/A

**Comment by lassekongo83** [comment]
`Frellwits Svenska Filter`

`Ett filter till uBlock Origin med målet att plocka bort svenska annonser, sponsrade artiklar, spårning, irritationer, viss integration av sociala medier etc.`

**Comment by DandelionSprout** [comment]
Tusen takk. Jeg har nå sendt inn dine forslag til AdGuard på Crowdin.
