### ISSUE TITLE
PBSwissTools.com - Broken page (Frellwit's Swedish Filter)

### ISSUE THREAD

**Issue by THEtomaso** [lassekongo83/Frellwits-filter-lists#96]
### Affected site:
`https://www.pbswisstools.com/`

### Issue:
The page is broken, due to a blocked third-party stylesheet.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **Frellwit's Swedish Filter**

### Problem rule:
`||fast.fonts.net/t/1.css$stylesheet,xmlhttprequest
`
### Possible fix:
`@@||fast.fonts.net/t/1.css$domain=pbswisstools.com`

..or perhaps delete all three `fast.fonts.com` blocking rules instead, as they might cause similar issues on other sites too?

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.17.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.27b2 (XUL)

**Comment by lassekongo83** [comment]
They just have overzealous requirements. 

That empty css file is used to track page views. `https://www.fonts.com/support/faq/installwebfonts`
