### ISSUE TITLE
Airam.fi - Missing scroll bar (Frellwit's Swedish Filter) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [lassekongo83/Frellwits-filter-lists#99]
### Affected site:
`https://www.airam.fi/`

### Issue:
Broken page (missing scroll bar), because of a blocked cookie consent message.

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **Frellwit's Swedish Filter**

### Problem rule:
`##.cookie-consent:not(body):not(html)`

### Possible fix:
`airam.fi#@#.cookie-consent:not(body):not(html)`

### Other problem filters:
* **AdGuard Annoyances filter** https://github.com/AdguardTeam/AdguardFilters/issues/73587/
`~raiba-ke-oa.de##.cookie-consent:not(body):not(html)`
`~yellowbrick.nl###cookie-consent`

* **EasyList Cookie List** / **Fanboy's Annoyance List** https://github.com/easylist/easylist/issues/7107/
`##.cookie-consent:not(body):not(html)`
`###cookie-consent`

* **I don't care about cookies** _(NOTIFIED)_
`~abconcerts.be##.footer + .cookie-consent`
`##.main .cookie-consent:not(.btn)`
`###__nuxt .cookie-consent`
`~telesec.de,~o2.fr,~qwic.de,~vu.nl,~indiearenabooth.com,~hscollective.org,~geefvoorzorgverleners.nl,~conradconnect.com,~biotechusa.hu,~biotechusa.fr,~officiallondontheatre.com,~nieuwspoort.nl,~atro-provita.de###cookie-consent:not(.content):not([class*="fancybox"])`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.17.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.28 (XUL)

**Comment by THEtomaso** [comment]
@lassekongo83:
Since you came up with a much better solution than I suggested, you should include this rule as well, to override the whitelistings, which probably will be added to **EasyList Cookie List**:
`airam.fi##[id="cookie-consent"]`

**Comment by lassekongo83** [comment]
I generally don't add rules regarding non-default lists.
